imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection:
        enabled: true
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  snc_redis.session.handler
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

sensio_framework_extra:
    view:
        annotations: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@ZenomaniaCoreBundle/Resources/views/form/theme/bootstrap_3_horizontal_layout.html.twig'
        - 'TetranzSelect2EntityBundle:Form:fields.html.twig'
    globals:
        breadcrumbs_service: "@breadcrumbs.service"

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_pgsql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        mapping_types:
            enum: string
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace: Zenomania\Migrations
    table_name: migration_versions
    name: Zenomania Migrations

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        user_thumb:
            quality: 75
            filters:
                thumbnail: { size: [200, 200], mode: outbound }
                auto_rotate: ~
    loaders:
        upload_files:
            filesystem:
                data_root: "%kernel.root_dir%/../web"

assetic:
    debug: '%kernel.debug%'
    use_controller: '%kernel.debug%'
    node: '%node_bin%'
    filters:
        cssrewrite: ~
        uglifyjs2:
            bin: '%uglifyjs_bin%'
        uglifycss:
            bin: '%uglifycss_bin%'

gregwar_captcha:
    width: 200
    height: 50
    length: 6,
    background_color: [255, 255, 255]
    as_url: true
    reload: true
    invalid_message: 'Введен неверный код картинки'

knp_menu:
    twig:
        template: knp_menu.html.twig
    templating: false
    default_renderer: twig

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "redis://%redis_server%"
            logging: "%kernel.debug%"
            options:
                prefix: "%project_name%:"
        cache:
            type: predis
            alias: cache
            dsn: "redis://%redis_server%/1"
            options:
                profile: 2.2
                prefix: "%project_name%:"
                connection_timeout: 10
                read_write_timeout: 30
        session:
            type: predis
            alias: session
            dsn: "redis://%redis_server%/2"
            options:
                prefix: "%project_name%:"
        cluster:
            type: predis
            alias: cluster
            dsn:
                - "redis://%redis_server%/3?weight=10"
                - "redis://%redis_server%/4?weight=5"
                - "redis://%redis_server%/5?weight=1"
            options:
                prefix: "%project_name%:"
    session:
        client: session
        locking: false
        ttl: "%auth_key_ttl%"

fos_rest:
    routing_loader:
        default_format: json
    view:
        formats:
            json: true
            xml: false
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
        empty_content: 204
#        view_response_listener: force
    service:
        view_handler: api.view_handler
    disable_csrf_role: ROLE_API
#    body_converter:
#        enabled: true
#        validate: true
#        validation_errors_argument: validationErrors
    param_fetcher_listener: true
    format_listener:
        enabled: true
        rules:
          - { path: '^/api/v1', fallback_format: 'json' }
          - { path: '^/', stop: true }
#    unauthorized_challenge: "Basic realm=\"Restricted Area\""
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
    exception:
        enabled: true
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
            'Zenomania\ApiBundle\Security\BadCredentialsException': 403
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    # these options are available in 2nd version of bundle
#    zone:
#        - { path: ^/api/* }
#    versioning: true

nelmio_api_doc:
    name: Zenomania API
    swagger:
        info:
            title: API
            description: Zenomania API
        api_version:  1
        api_base_path: /api/v1
        swagger_version: '2.0'

sms_service:
    enabled: true
    clients:
        default:
            alias: sms16
        infobip:
            alias: infobip
        smstraffic:
            alias: smstraffic
    channels:
        infobip:
            class: Zenomania\CoreBundle\Service\Sms\Gateway\Infobip
            gateway_url: https://api.infobip.com/sms/1/text/single
            originator: "%sms_infobip_originator%"
            login: "%sms_infobip_login%"
            password: "%sms_infobip_password%"
        smstraffic:
            class: Zenomania\CoreBundle\Service\Sms\Gateway\Smstraffic
            gateway_url: https://api.smstraffic.ru/multi.php
            originator: "%sms_smstraffic_originator%"
            login: "%sms_smstraffic_login%"
            password: "%sms_smstraffic_password%"
        sms16:
            class: Zenomania\CoreBundle\Service\Sms\Gateway\Sms16
            gateway_url: https://new.sms16.ru/get/send.php
            originator: "%sms_sms16_originator%"
            login: "%sms_sms16_login%"
            password: "%sms_sms16_password%"

doctrine_mongodb:
    connections:
        default:
            server: "mongodb://%mongodb_host%:%mongodb_port%"
            options: {}
    default_database: "zenomania_%kernel.environment%"
    document_managers:
        default:
            auto_mapping: true
    auto_generate_hydrator_classes: true
