zenomania_api:
    resource: "@ZenomaniaApiBundle/Resources/config/routing.yml"
    prefix:   /api/v1
zenomania_core:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing.yml"
    prefix:   /
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
