zenomania_api:
    resource: "@ZenomaniaApiBundle/Resources/config/routing.yml"
    prefix:   /api/v1

zenomania_core:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing.yml"
    prefix:   /
