Zenomania\CoreBundle\Entity\Activity:
    type: entity
    table: activity
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 1024
            options:
                fixed: false
    manyToMany:
        person:
            targetEntity: Person
            cascade: {  }
            fetch: LAZY
            mappedBy: activity
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
