Zenomania\CoreBundle\Entity\BadgeType:
    type: entity
    table: null
    repositoryClass: Zenomania\CoreBundle\Repository\BadgeTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            length: 255
        sort:
            type: integer
            options:
                default: '0'
    lifecycleCallbacks: {  }
