Zenomania\CoreBundle\Entity\Club:
    type: entity
    table: club
    repositoryClass: Zenomania\CoreBundle\Repository\ClubRepository
    indexes:
        FK_club_sport:
            columns:
                - sport
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
        site:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        vkGroup:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: vk_group
        fbGroup:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: fb_group
        twitterGroup:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: twitter_group
        instagramGroup:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: instagram_group
        youtubeGroup:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
            column: youtube_group
        ytUploadPlaylist:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
            column: yt_upload_playlist
        logoImg:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
            column: logo_img
        lineUpAvailable:
            type: boolean
            nullable: false
            options:
                default: false
            column: line_up_available
            comment: 'Показывать ли стартовый состав матча для клуба'
    manyToOne:
        sport:
            targetEntity: Zenomania\CoreBundle\Entity\Sport
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sport:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    oneToMany:
        person:
            targetEntity: Zenomania\CoreBundle\Entity\Person
            cascade: {  }
            fetch: LAZY
            mappedBy: clubOwner
            inversedBy: null
            joinTable: null
            orderBy: null
        players:
            targetEntity: Zenomania\CoreBundle\Entity\Player
            cascade: {  }
            fetch: LAZY
            mappedBy: club
            inversedBy: null
            joinTable: null
            orderBy:
                lastname: ASC
    lifecycleCallbacks: {  }
