Zenomania\CoreBundle\Entity\DeliveryType:
    type: entity
    table: delivery_type
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            length: 255
    lifecycleCallbacks: {  }
