Zenomania\CoreBundle\Entity\Document:
    type: entity
    table: document
    uniqueConstraints:
        person_id_type:
            columns:
                - person_id
                - type
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        personId:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: person_id
        type:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                comment: 'тип документа'
        serial:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                comment: 'серия документа'
                default: '0'
        number:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                comment: 'номер документа'
                default: '0'
        date:
            type: date
            nullable: false
            options:
                comment: 'дата выдачи'
        subCode:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
                comment: 'код подразделения'
                default: '0'
            column: sub_code
        given:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
                comment: 'кем выдан'
                default: '0'
    lifecycleCallbacks: {  }
