Zenomania\CoreBundle\Entity\Education:
    type: entity
    table: education
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 128
            options:
                fixed: false
    lifecycleCallbacks: {  }
