Zenomania\CoreBundle\Entity\EmailFriendsReference:
    type: entity
    table: email_friends_reference
    indexes:
        email:
            columns:
                - email
        person_id:
            columns:
                - person_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
                default: '0'
        subject:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
                default: ''
        body:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        dt:
            type: datetime
            nullable: false
    manyToOne:
        person:
            targetEntity: Person
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                person_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
