Zenomania\CoreBundle\Entity\EmailOut:
    type: entity
    table: email_out
    indexes:
        FK_email_out_to_person:
            columns:
                - to_person
        FK_email_out_from_person:
            columns:
                - from_person
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dt:
            type: datetime
            nullable: false
        fromEmail:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: from_email
        toEmail:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
            column: to_email
        subject:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        body:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        type:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
        sended:
            type: boolean
            nullable: false
            options:
                default: '0'
    manyToOne:
        fromPerson:
            targetEntity: Person
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                from_person:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        toPerson:
            targetEntity: Person
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                to_person:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
