Zenomania\CoreBundle\Entity\EmailDispatch:
    type: entity
    table: email_dispatch
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        subject:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
                default: ''
        body:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
        source:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: html
        category:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: info
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: Рас-рас-рассылка
        active:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: 'N'
        createdDate:
            type: datetime
            nullable: true
            options:
                comment: 'Дата создания'
            column: created_date
        createdActor:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: created_actor
    lifecycleCallbacks: {  }
