Zenomania\CoreBundle\Entity\EventPlayerForecast:
    type: entity
    table: event_player_forecast
    repositoryClass: Zenomania\CoreBundle\Repository\EventPlayerForecastRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        createdOn:
            type: datetime
            nullable: false
            column: created_on
        updatedOn:
            type: datetime
            nullable: true
            column: updated_on
        status:
            type: integer
            nullable: true
            options:
                unsigned: true
        isMvp:
            type: boolean
            nullable: false
            options:
                default: false
            column: is_mvp
    manyToOne:
        event:
            targetEntity: Zenomania\CoreBundle\Entity\Event
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                event_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        player:
            targetEntity: Zenomania\CoreBundle\Entity\Player
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                player_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        user:
            targetEntity: Zenomania\CoreBundle\Entity\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
