Zenomania\CoreBundle\Entity\EventForecast:
    type: entity
    table: event_forecast
    repositoryClass: Zenomania\CoreBundle\Repository\EventForecastRepository
    indexes:
        FK_person_event_forecast_event:
            columns:
                - event_id
        person_event_forecast__dt:
            columns:
                - created_on
        IDX_89ADA1AA217BBB47:
            columns:
                - person_id
    uniqueConstraints:
        person_event:
            columns:
                - person_id
                - event_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        scoreHome:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: score_home
        scoreGuest:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: score_guest
        scoreInRounds:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: score_in_round
        createdOn:
            type: datetime
            nullable: false
            column: created_on
        updatedOn:
            type: datetime
            nullable: true
            column: updated_on
        status:
            type: integer
            nullable: true
            options:
                unsigned: true
    manyToOne:
        event:
            targetEntity: Event
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                event_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        person:
            targetEntity: Person
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                person_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        user:
            targetEntity: Zenomania\CoreBundle\Entity\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
