Zenomania\CoreBundle\Entity\Event:
    type: entity
    table: event
    repositoryClass: Zenomania\CoreBundle\Repository\EventRepository
    indexes:
        FK_event_club:
            columns:
                - club_home
        FK_event_club_2:
            columns:
                - club_guest
        FK_event_place:
            columns:
                - place_id
        FK_event_sport:
            columns:
                - sport_id
        FK_event_season:
            columns:
                - season_id
        FK_event_mvp:
            columns:
                - mvp
        event__date:
            columns:
                - date
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        date:
            type: datetime
            nullable: false
        purchasable:
            type: boolean
            nullable: false
            options:
                default: '0'
        chship:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: NA
        scoreHome:
            type: smallint
            nullable: true
            options:
                default: 0
            column: score_home
        scoreGuest:
            type: smallint
            nullable: true
            options:
                default: 0
            column: score_guest
        scoreSaved:
            type: smallint
            nullable: true
            options:
                default: 0
            column: score_saved
        isLineUp:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_line_up
        scoreInRounds:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
            column: score_in_round
    oneToMany:
        lineUp:
            targetEntity: Zenomania\CoreBundle\Entity\LineUp
            cascade: ["persist"]
            fetch: LAZY
            mappedBy: event
            inversedBy: null
            joinTable: null
            orderBy: null
    manyToOne:
        clubHome:
            targetEntity: Club
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                club_home:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        clubGuest:
            targetEntity: Club
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                club_guest:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        place:
            targetEntity: Place
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                place_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        season:
            targetEntity: Zenomania\CoreBundle\Entity\Season
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                season_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        sport:
            targetEntity: Sport
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sport_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        mvp:
            targetEntity: Player
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                mvp:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
