Zenomania\CoreBundle\Entity\FanCard:
    type: entity
    table: fan_card
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        number:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: '0'
        innerNumber:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: '0'
            column: inner_number
        state:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: Active
        bestBeforeDate:
            type: date
            nullable: false
            column: best_before_date
        spentSum:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            options:
                comment: 'Потрачено денег по этой карте'
                default: '0.00'
            column: spent_sum
        points:
            type: decimal
            nullable: false
            precision: 10
            scale: 2
            options:
                comment: 'Начисленные баллы по этой карте'
                default: '0.00'
        givenDate:
            type: date
            nullable: false
            column: given_date
        blockedReason:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
            column: blocked_reason
        blockedReasonComment:
            type: string
            nullable: true
            length: 512
            options:
                fixed: false
            column: blocked_reason_comment
    manyToMany:
        person:
            targetEntity: Person
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: fancard
            joinTable:
                name: fan_card_person
                joinColumns:
                    -
                        name: fancard_id
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    -
                        name: person_id
                        referencedColumnName: id
                        onDelete: CASCADE
            orderBy: null
    lifecycleCallbacks: {  }
