Zenomania\CoreBundle\Entity\Item:
    type: entity
    table: item
    indexes:
        FK_item_item_how2get:
            columns:
                - how2get
        FK_item_event:
            columns:
                - event_id
        item__sortorder_ix:
            columns:
                - sortorder
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        active:
            type: boolean
            nullable: false
            options:
                default: '0'
        parentItem:
            type: integer
            nullable: true
            options:
                unsigned: true
            column: parent_item
        rule:
            type: integer
            nullable: true
            options:
                unsigned: true
        outerId:
            type: integer
            nullable: false
            options:
                unsigned: true
            column: outer_id
        appId:
            type: integer
            nullable: false
            options:
                unsigned: true
                comment: 'ид внешнего приложения'
            column: app_id
        pricePoints:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                comment: 'цена в баллах'
                default: '0'
            column: price_points
        priceRub:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                comment: 'цена в рублях'
                default: '0'
            column: price_rub
        name:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
                default: Приз
        img:
            type: string
            nullable: false
            length: 1024
            options:
                fixed: false
                default: /static/img/prize1.png
        sortorder:
            type: boolean
            nullable: true
            options:
                default: '0'
    manyToOne:
        event:
            targetEntity: Event
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                event_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        how2get:
            targetEntity: ItemHow2get
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                how2get:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
