Zenomania\CoreBundle\Entity\OrderStatus:
    type: entity
    table: null
    repositoryClass: Zenomania\CoreBundle\Repository\OrderStatusRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            length: 255
        code:
            type: string
            length: 255
    lifecycleCallbacks: {  }
