Zenomania\CoreBundle\Entity\Payment:
    type: entity
    table: null
    repositoryClass: Zenomania\CoreBundle\Repository\PaymentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
    fields:
        amount:
            type: float
        type:
            type: string
            length: 255
        createdOn:
            type: datetime
            nullable: false
            column: created_on
    manyToOne:
        user:
            targetEntity: Zenomania\CoreBundle\Entity\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
