Zenomania\CoreBundle\Entity\PersonProgress:
    type: entity
    table: person_progress
    indexes:
        FK_person_progress__progress_id:
            columns:
                - progress_id
        FK_person_progress__person_id:
            columns:
                - person_id
    id:
        personId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: person_id
        progressId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: progress_id
    fields:
        dt:
            type: datetime
            nullable: false
    lifecycleCallbacks: {  }
