Zenomania\CoreBundle\Entity\PersonSubs:
    type: entity
    table: person_subs
    id:
        personId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: person_id
        listId:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            column: list_id
    fields:
        enabled:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
