Zenomania\CoreBundle\Entity\Person:
    type: entity
    table: person
    repositoryClass: Zenomania\CoreBundle\Repository\PersonRepository
    indexes:
        FK_person_city:
            columns:
                - city
        FK_person_district:
            columns:
                - district
        person__email:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        promoCode:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: promo_code
        avatar:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        firstName:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
            column: first_name
        lastName:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
            column: last_name
        middleName:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
            column: middle_name
        sex:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
        familystatus:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
        bdate:
            type: date
            nullable: true
        comesBy:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
            column: comes_by
        address:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
        mobile:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        mobileAvailable:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
            column: mobile_available
        email:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        mobileAdd:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: mobile_add
        emailAdd:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: email_add
        notes:
            type: text
            nullable: true
            length: 255
            options:
                fixed: false
        emailAllowed:
            type: boolean
            nullable: false
            options:
                default: true
            column: email_allowed
        smsAllowed:
            type: boolean
            nullable: false
            options:
                default: true
            column: sms_allowed
        regDate:
            type: datetime
            nullable: true
            column: reg_date
        regActor:
            type: integer
            nullable: true
            options:
                unsigned: true
            column: reg_actor
        regType:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
                default: other
            column: reg_type
        regTypeName:
            type: string
            nullable: true
            length: 256
            options:
                fixed: false
            column: reg_type_name
        emailConfirmed:
            type: boolean
            nullable: false
            options:
                default: false
            column: email_confirmed
    manyToOne:
        city:
            targetEntity: City
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                city:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        clubOwner:
            targetEntity: Zenomania\CoreBundle\Entity\Club
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: person
            joinColumns:
                club_owner:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        district:
            targetEntity: District
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                district:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    manyToMany:
        fancard:
            targetEntity: FanCard
            cascade: {  }
            fetch: LAZY
            mappedBy: person
            inversedBy: null
            joinTable: null
            orderBy: null
        activity:
            targetEntity: Activity
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: person
            joinTable:
                name: person_activity
                joinColumns:
                    -
                        name: person_id
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    -
                        name: activity_id
                        referencedColumnName: id
                        onDelete: CASCADE
            orderBy: null
    oneToOne:
        user:
            targetEntity: Zenomania\CoreBundle\Entity\User
            inversedBy: person
            joinColumn:
              name: user_id
              referencedColumnName: id
    lifecycleCallbacks: {  }
