Zenomania\CoreBundle\Entity\PersonPoints:
    type: entity
    table: person_points
    repositoryClass: Zenomania\CoreBundle\Repository\PersonPointsRepository
    entityListeners:
        Zenomania\CoreBundle\Entity\Listener\PersonPointsListener: ~
    indexes:
        person_points__person_id:
            columns:
                - person_id
        person_points__type:
            columns:
                - type
        person_points__season_id:
            columns:
                - season_id
        person_points__user_id:
            columns:
                - user_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        points:
            type: smallint
            nullable: false
            options:
                unsigned: false
                default: '0'
        type:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
        state:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: none
        dt:
            type: datetime
            nullable: false
        operation_type:
            type: string
            nullable: true
            length: null
            options:
                fixed: false
    manyToOne:
        season:
            targetEntity: Zenomania\CoreBundle\Entity\Season
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                season_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        person:
            targetEntity: Person
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                person_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        user:
            targetEntity: Zenomania\CoreBundle\Entity\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
