Zenomania\CoreBundle\Entity\Player:
    type: entity
    table: player
    indexes:
        FK_player_club:
            columns:
                - club
        player_name__idx:
            columns:
                - lastname
                - firstname
                - middlename
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstname:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: имя
        lastname:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: фамилия
        middlename:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: отчество
        birthdate:
            type: date
            nullable: true
            options:
                comment: 'Дата рождения игрока'
        photo:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: фото
        isActive:
            type: boolean
            nullable: true
            comment: 'активен ли пользователь'
            column: is_active
        createdOn:
            type: datetime
            nullable: true
            column: created_on
            comment: 'дата создания'
        updatedOn:
            type: datetime
            nullable: true
            comment: 'дата модификации'
            column: updated_on
    manyToOne:
        club:
            targetEntity: Zenomania\CoreBundle\Entity\Club
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: players
            joinColumns:
                club:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
