Zenomania\CoreBundle\Entity\PromoCode:
    type: entity
    table: promo_code
    indexes:
        promo_code__season:
            columns:
                - season_id
        promo_code__ticket:
            columns:
                - ticket
        promo_code__barcode:
            columns:
                - barcode
        promo_code__email:
            columns:
                - email
    uniqueConstraints:
        code_ticket:
            columns:
                - code
                - ticket
        sms:
            columns:
                - sms
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        code:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
        used:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        electronic:
            type: boolean
            nullable: false
            options:
                default: '0'
        email:
            type: integer
            nullable: true
            options:
                unsigned: true
        barcode:
            type: bigint
            nullable: true
            options:
                unsigned: true
        outerId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: outer_id
        activatedDt:
            type: datetime
            nullable: true
            column: activated_dt
    manyToOne:
        season:
            targetEntity: Zenomania\CoreBundle\Entity\Season
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                season_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        sms:
            targetEntity: PromoSmsIn
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sms:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        ticket:
            targetEntity: Ticket
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                ticket:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
