Zenomania\CoreBundle\Entity\PromoCouponAction:
    type: entity
    table: promo_coupon_action
    repositoryClass: Zenomania\CoreBundle\Repository\PromoCouponActionRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        caption:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
        endDt:
            type: datetime
            nullable: true
            column: end_dt
        isBlocked:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: is_blocked
        allowedDays:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: allowed_days
    lifecycleCallbacks: {  }
