Zenomania\CoreBundle\Document\ProviderSubscription:
    collection: provider_subs
    repositoryClass: Zenomania\CoreBundle\Repository\Document\ProviderSubscriptionRepository
    indexes:
        event_id:
            keys:
                event_id: 1
        cardcode:
            keys:
                cardcode: 1
    fields:
        id:
            id: true
        cardcode:
            type: string
        event_id:
            type: int
        sub_id:
            type: int
        dt_enter:
            type: date
        price:
            type: float
        row:
            type: string
        seat:
            type: string
        sector:
            type: string
        created_on:
            type: date
        updated_on:
            type: date
        status:
            type: string
