Zenomania\CoreBundle\Entity\PushDeviceId:
    type: entity
    table: push_device_id
    indexes:
        FK_push_device_id_person:
            columns:
                - person_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        deviceId:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false
            column: device_id
        os:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
    manyToOne:
        person:
            targetEntity: Person
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                person_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
