Zenomania\CoreBundle\Entity\Role:
    type: entity
    table: role
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        role:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    manyToMany:
        users:
            targetEntity: Zenomania\CoreBundle\Entity\Actor
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: roles
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
