Zenomania\CoreBundle\Entity\SocialPost:
    type: entity
    table: social_post
    indexes:
        social_post__moder:
            columns:
                - moder
        social_post__group_id:
            columns:
                - group_id
        social_post__likes:
            columns:
                - likes
        social_post__views:
            columns:
                - views
        social_post__club_id:
            columns:
                - club_id
        social_post__date:
            columns:
                - date
        social_post__network:
            columns:
                - network
    uniqueConstraints:
        network_group_id_outerid:
            columns:
                - network
                - group_id
                - outerid
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        clubId:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
            column: club_id
        network:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
        groupId:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: ''
            column: group_id
        outerid:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: ''
        date:
            type: datetime
            nullable: true
        text:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        textbig:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        link:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        pic:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        picbig:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
        reposts:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        likes:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        comments:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        views:
            type: integer
            nullable: false
            options:
                unsigned: true
                default: '0'
        moder:
            type: boolean
            nullable: false
            options:
                comment: 'статус модерации'
                default: '0'
    lifecycleCallbacks: {  }
