Zenomania\CoreBundle\Entity\SocialRepost:
    type: entity
    table: social_repost
    repositoryClass: Zenomania\CoreBundle\Repository\SocialRepostRepository
    indexes:
        FK_social_repost_person:
            columns:
                - user_id
        IDX_C37F24194B89032C:
            columns:
                - news_id
    uniqueConstraints:
        news_id_vk_id:
            columns:
                - news_id
                - vk_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        vkId:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: vk_id
        dt:
            type: datetime
            nullable: true
            options:
                comment: 'Дата репоста'
            column: dt
        createdOn:
            type: datetime
            nullable: true
            column: created_on
            comment: 'дата создания'
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        news:
            targetEntity: News
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                news_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
