Zenomania\CoreBundle\Entity\SocialRepost:
    type: entity
    table: social_repost
    indexes:
        FK_social_repost_person:
            columns:
                - person_id
        IDX_C37F24194B89032C:
            columns:
                - post_id
    uniqueConstraints:
        post_id_user_outerid:
            columns:
                - post_id
                - user_outerid
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        network:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
        userOuterid:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: user_outerid
        repostOuterid:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: repost_outerid
        repostDt:
            type: datetime
            nullable: true
            options:
                comment: 'Дата репоста'
            column: repost_dt
    manyToOne:
        person:
            targetEntity: Person
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                person_id:
                    referencedColumnName: id
            orphanRemoval: false
        post:
            targetEntity: SocialPost
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                post_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
