Zenomania\CoreBundle\Entity\SubsList:
    type: entity
    table: subs_list
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
                default: ''
        outerId:
            type: string
            nullable: false
            length: 256
            options:
                fixed: false
                default: ''
            column: outer_id
    lifecycleCallbacks: {  }
