Zenomania\CoreBundle\Entity\Subscription:
    type: entity
    table: subscription
    repositoryClass: Zenomania\CoreBundle\Repository\SubscriptionRepository
    indexes:
        FK_subscription_person:
            columns:
                - person_id
        FK_subscription_season:
            columns:
                - season_id
    uniqueConstraints:
        subscription__stand_sector_row_seat:
            columns:
                - stand
                - sector
                - row
                - seat
        subscription__serial_number:
            columns:
                - serial
                - number
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        mifare:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        serial:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
        number:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        stand:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        sector:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        row:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        seat:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        price:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        note:
            type: string
            nullable: false
            length: 512
            options:
                fixed: false
                default: ''
    manyToOne:
        person:
            targetEntity: Person
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                person_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        season:
            targetEntity: Zenomania\CoreBundle\Entity\Season
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                season_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
