Zenomania\CoreBundle\Entity\Ticket:
    type: entity
    table: ticket
    repositoryClass: Zenomania\CoreBundle\Repository\TicketRepository
    indexes:
        ticket__event:
            columns:
                - event_id
        ticket__state:
            columns:
                - state
        ticket__number:
            columns:
                - number
        ticket__person_id:
            columns:
                - person_id
    uniqueConstraints:
        ticket__stand_sector_row_seat:
            columns:
                - event_id
                - stand
                - sector
                - row
                - seat
        ticket__event_id_number:
            columns:
                - event_id
                - number
        ticket__event_id_by_person:
            columns:
                - person_id
                - event_id
                - number
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        serial:
            type: string
            nullable: false
            length: 10
            options:
                fixed: false
                default: ''
        number:
            type: bigint
            nullable: false
            options:
                unsigned: true
        stand:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: ''
        sector:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: ''
        row:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
                default: ''
        seat:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        price:
            type: float
            nullable: false
            precision: 10
            scale: 0
            options:
                default: '0'
        state:
            type: string
            nullable: false
            length: null
            options:
                fixed: false
                default: idle
    manyToOne:
        event:
            targetEntity: Event
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                event_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        person:
            targetEntity: Person
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                person_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
