Zenomania\CoreBundle\Entity\UserBadge:
    type: entity
    table: user_badge
    repositoryClass: Zenomania\CoreBundle\Repository\UserBadgeRepository
    id:
        id:
            type: integer
            id: true
            options:
                unsigned: true
            generator:
                strategy: IDENTITY
    fields:
        points:
            type: integer
        createdOn:
            type: datetime
            column: dt
            comment: 'дата создания'
    manyToOne:
        badgeId:
            targetEntity: Badge
            cascade: {  }
            mappedBy: null
            inversedBy: null
            fetch: LAZY
            joinColumns:
                badge_id:
                    nullable: false
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        user:
            targetEntity: Zenomania\CoreBundle\Entity\User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
    lifecycleCallbacks: {  }
