Zenomania\CoreBundle\Entity\User:
    type: entity
    table: users
    repositoryClass: Zenomania\CoreBundle\Repository\UserRepository
    entityListeners:
        Zenomania\CoreBundle\Entity\Listener\UserListener: ~
    indexes:
        role_id__idx:
            columns:
                - role_id
        status_id__idx:
            columns:
                - status_id
        login_credenitials__idx:
            columns:
                - login
                - password
        phone__idx:
            columns:
                - phone
        user_name__idx:
            columns:
                - lastname
                - firstname
                - middlename
    uniqueConstraints:
        email__idx:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: идентификатор
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstname:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: имя
        lastname:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: фамилия
        middlename:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: отчество
        login:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: логин
        email:
            type: string
            nullable: true
            length: 255
            fixed: false
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
        birthDate:
            type: date
            nullable: true
            comment: 'дата рождения'
            column: birth_date
        avatar:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: фото
        avatarSmall:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: 'фото меньшего размера'
            column: avatar_small
        phone:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: 'телефон'
        lastLoginOn:
            type: datetime
            nullable: true
            comment: 'последняя авторизация'
            column: last_login_on
        createdOn:
            type: datetime
            nullable: true
            column: created_on
            comment: 'дата создания'
        updatedOn:
            type: datetime
            nullable: true
            comment: 'дата модификации'
            column: updated_on
        mailNotification:
            type: boolean
            nullable: true
            comment: 'уведмоления включены'
            column: mail_notification
        mustChangePasswd:
            type: boolean
            nullable: true
            comment: 'нужно сменить пароль'
            column: must_change_passwd
        passwdChangedOn:
            type: datetime
            nullable: true
            comment: 'пароль изменен'
            column: passwd_changed_on
        isActive:
            type: boolean
            nullable: true
            comment: 'активен ли пользователь'
            column: is_active
        isBlocked:
            type: boolean
            nullable: false
            options:
                default: false
            comment: 'заблокирован ли пользователь'
            column: is_blocked
        isDeleted:
            type: boolean
            nullable: false
            options:
                default: false
            comment: 'удален ли пользователь'
            column: is_deleted
        verifyEmailUuid:
            type: string
            nullable: true
            length: 50
            fixed: true
            comment: 'код для сброса пароля'
            column: verify_email_uuid
        isSuperuser:
            type: boolean
            nullable: true
            comment: суперпользователь
            column: is_superuser
    manyToOne:
        status:
            targetEntity: UserStatus
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                status_id:
                    nullable: false
                    referencedColumnName: id
                    onDelete: RESTRICT
            orphanRemoval: false
        role:
            targetEntity: UserRole
            cascade: {  }
            mappedBy: null
            inversedBy: null
            fetch: EAGER
            joinColumns:
                role_id:
                    nullable: false
                    referencedColumnName: id
                    onDelete: RESTRICT
            orphanRemoval: false
    oneToMany:
        accounts:
            targetEntity: Zenomania\CoreBundle\Entity\SocialAccount
            mappedBy: user
            inversedBy: null
            cascade: ["persist"]
            orphanRemoval: false
    oneToOne:
        person:
          targetEntity: Zenomania\CoreBundle\Entity\Person
          mappedBy: user
    lifecycleCallbacks: {  }
