api_security:
    type: rest
    prefix: 'auth'
    resource: "Zenomania\\ApiBundle\\Controller\\SecurityController"
api_profile:
    type: rest
    resource: "Zenomania\\ApiBundle\\Controller\\ProfileController"
api_ticket:
    type: rest
    resource: "Zenomania\\ApiBundle\\Controller\\TicketController"
api_subscription:
    type: rest
    resource: "Zenomania\\ApiBundle\\Controller\\SubscriptionController"
api_invite:
    type: rest
    resource: "Zenomania\\ApiBundle\\Controller\\InviteController"
api_event:
    type: rest
    resource: "Zenomania\\ApiBundle\\Controller\\EventController"
