api_security:
    type: rest
    prefix: 'auth'
    resource: "Zenomania\\ApiBundle\\Controller\\SecurityController"
api_profile:
    type: rest
    resource: "Zenomania\\ApiBundle\\Controller\\ProfileController"
api_ticket:
    type: rest
    resource: "Zenomania\\ApiBundle\\Controller\\TicketController"
api_subscription:
    type: rest
    resource: "Zenomania\\ApiBundle\\Controller\\SubscriptionController"
api_profile_social:
    type: rest
    prefix: 'profile/social'
    resource: "Zenomania\\ApiBundle\\Controller\\ProfileSocialController"
api_invite:
    type: rest
    resource: "Zenomania\\ApiBundle\\Controller\\InviteController"
api_event:
    type: rest
    resource: "Zenomania\\ApiBundle\\Controller\\EventController"
api_points:
    type: rest
    resource: "Zenomania\\ApiBundle\\Controller\\PointsController"
api_promocoupon:
    type: rest
    resource: "Zenomania\\ApiBundle\\Controller\\PromoCouponController"
api_ratings:
    type: rest
    resource: "Zenomania\\ApiBundle\\Controller\\RatingsController"
api_players:
    type: rest
    resource: "Zenomania\\ApiBundle\\Controller\\PlayerController"
api_badge:
    type: rest
    resource: "Zenomania\\ApiBundle\\Controller\\BadgeController"
api_news:
    type: rest
    resource: "Zenomania\\ApiBundle\\Controller\\NewsController"
api_orders:
    type: rest
    resource: "Zenomania\\ApiBundle\\Controller\\OrdersController"
api_product:
    type: rest
    resource: "Zenomania\\ApiBundle\\Controller\\ProductController"
api_users:
    type: rest
    resource: "Zenomania\\ApiBundle\\Controller\\UserController"