imports:
    - {resource: "services/transformers.yml" }
    - {resource: "services/clients.yml" }
    - {resource: "services/forms.yml" }

services:
    apitoken_authenticator:
        class:  Zenomania\ApiBundle\Security\ApiTokenAuthenticator
        public: false
    api_token_user_provider:
        class: Zenomania\ApiBundle\Security\ApiTokenUserProvider
        arguments: ['@repository.user_repository', '@api.key_provider']
        public: false
    apikey_authenticator:
        class: Zenomania\ApiBundle\Security\ApiKeyAuthenticator
        public: false
    api_key_user_provider:
        class: Zenomania\ApiBundle\Security\ApiKeyUserProvider
        arguments: ['@api.key_provider']
        public: false
    api.response_handler:
        class: Zenomania\ApiBundle\View\ResponseViewHandler
    api.exception_normalizer:
        class: Zenomania\ApiBundle\Normalizer\ExceptionNormalizer
        public: false
        tags: [api.normalizer]
    api.exception_subscriber:
        class: Zenomania\ApiBundle\EventSubscriber\ExceptionListener
        arguments:
            - '@core.serializer.default'
            - '@logger'
        tags:
            - { name: kernel.event_subscriber }
    api.view_handler:
        parent: fos_rest.view_handler.default
        calls:
            - ['registerHandler', [ 'json', ['@api.response_handler', 'createResponse'] ] ]
    api.auth_service:
        class: Zenomania\ApiBundle\Service\Authenticate
        arguments: ['@repository.user_repository', '@security.password_encoder']
    api.tickets:
        class: Zenomania\ApiBundle\Service\Tickets
        arguments: ['@repository.ticket_repository', '@repository.person_points_repository', '@repository.event_attendance_repository']
    api.subscriptions:
        class: Zenomania\ApiBundle\Service\Subscriptions
        arguments: ['@repository.person_points_repository', '@repository.subscription_repository']
    api.auth_options:
        class: Zenomania\ApiBundle\Service\AuthenticateOptions
        arguments: [{'auth_key_ttl': "%auth_key_ttl%"}]
    api.invite_service:
        class: Zenomania\ApiBundle\Service\Invite\InviteByEmail
        arguments: ['@mailer', '%mailer_from%', '@templating']
    api.invite_bonus_service:
        class: Zenomania\ApiBundle\Service\Invite\BonusPoints
        arguments:
            - '@repository.user_referral_code_repository'
            - '@repository.person_points_repository'
    api.key_provider:
        class: Zenomania\ApiBundle\Service\ApiKeyProvider
        arguments: ['@core.service.token.storage', '@api.auth_options']
    test_entity_factory:
        class: Zenomania\ApiBundle\Tests\TestEntityFactory
        arguments: ['@doctrine.orm.entity_manager', '@user.service', '@service_container']
    api.profile_social_bind:
        class: Zenomania\ApiBundle\Service\Social\BonusPoints
        arguments: ['@repository.person_points_repository']
    api.profile_social_update:
        class: Zenomania\ApiBundle\Service\Social\UpdateSocialInfo
        arguments: ['@repository.social_account_repository', '@api.profile_social_bind']
    user.profile:
        class: Zenomania\ApiBundle\Form\Model\UserProfile
    user.entity:
        class: Zenomania\CoreBundle\Entity\User
    api.user_profile:
        class: Zenomania\ApiBundle\Service\UserProfile
        arguments: ['@user.service','@repository.person_repository']
    api.person_points:
        class: Zenomania\ApiBundle\Service\PersonPoints
        arguments: ['@repository.person_points_repository']
    api.promocoupon:
        class: Zenomania\ApiBundle\Service\PromoCoupon
        arguments: ['@repository.promocoupon_repository', '@repository.person_points_repository']