<?php

namespace Zenomania\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20170728134156 extends AbstractMigration
{
    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE TABLE activity (id SERIAL NOT NULL, name VARCHAR(256) NOT NULL, description VARCHAR(1024) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE actor (id SERIAL NOT NULL, club_owner INT DEFAULT NULL, person INT DEFAULT NULL, username VARCHAR(50) NOT NULL, password VARCHAR(512) NOT NULL, token VARCHAR(20) DEFAULT NULL, refrr INT DEFAULT NULL, should_change_pwd BOOLEAN DEFAULT \'false\' NOT NULL, auth_token VARCHAR(256) DEFAULT NULL, vk_id VARCHAR(128) DEFAULT NULL, fb_id VARCHAR(128) DEFAULT NULL, reset_token CHAR(6) DEFAULT NULL, reg_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, reg_source VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_447556F96F0ECCCE ON actor (club_owner)');
        $this->addSql('CREATE UNIQUE INDEX actor__club_owner_username ON actor (club_owner, username)');
        $this->addSql('CREATE UNIQUE INDEX actor__person ON actor (person)');
        $this->addSql('CREATE UNIQUE INDEX actor__club_owner_vk_id ON actor (club_owner, vk_id)');
        $this->addSql('CREATE UNIQUE INDEX actor__club_owner_fb_id ON actor (club_owner, fb_id)');
        $this->addSql('COMMENT ON COLUMN actor.reg_date IS \'Дата регистрации\'');
        $this->addSql('CREATE TABLE auth_log (id SERIAL NOT NULL, person_id INT DEFAULT NULL, login VARCHAR(50) NOT NULL, status TEXT NOT NULL, dt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX auth_log__dt ON auth_log (dt)');
        $this->addSql('CREATE INDEX auth_log__person_id ON auth_log (person_id)');
        $this->addSql('COMMENT ON COLUMN auth_log.status IS \'(DC2Type:simple_array)\'');
        $this->addSql('CREATE TABLE city (id SERIAL NOT NULL, name VARCHAR(256) DEFAULT \'\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE client_application (id SERIAL NOT NULL, club_owner INT DEFAULT NULL, outer_service VARCHAR(25) NOT NULL, name VARCHAR(50) DEFAULT NULL, password VARCHAR(50) DEFAULT NULL, auth_key VARCHAR(50) DEFAULT NULL, url VARCHAR(256) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX FK_client_application_club ON client_application (club_owner)');
        $this->addSql('CREATE TABLE club (id SERIAL NOT NULL, sport INT DEFAULT NULL, name VARCHAR(128) DEFAULT NULL, site VARCHAR(256) DEFAULT NULL, vk_group VARCHAR(20) DEFAULT \'\' NOT NULL, fb_group VARCHAR(20) DEFAULT \'\' NOT NULL, twitter_group VARCHAR(20) DEFAULT \'\' NOT NULL, instagram_group VARCHAR(20) DEFAULT \'\' NOT NULL, youtube_group VARCHAR(256) DEFAULT \'\' NOT NULL, yt_upload_playlist VARCHAR(256) DEFAULT \'\' NOT NULL, index_enabled BOOLEAN DEFAULT \'false\' NOT NULL, logo_img VARCHAR(256) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX FK_club_sport ON club (sport)');
        $this->addSql('CREATE TABLE country (id SERIAL NOT NULL, name VARCHAR(50) DEFAULT \'\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE district (id SERIAL NOT NULL, name VARCHAR(256) DEFAULT \'\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE document (id SERIAL NOT NULL, person_id INT DEFAULT 0 NOT NULL, type VARCHAR(255) NOT NULL, serial VARCHAR(50) DEFAULT \'0\' NOT NULL, number VARCHAR(50) DEFAULT \'0\' NOT NULL, date DATE NOT NULL, sub_code VARCHAR(128) DEFAULT \'0\' NOT NULL, given VARCHAR(128) DEFAULT \'0\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX document__person_id_type ON document (person_id, type)');
        $this->addSql('COMMENT ON COLUMN document.type IS \'тип документа\'');
        $this->addSql('COMMENT ON COLUMN document.serial IS \'серия документа\'');
        $this->addSql('COMMENT ON COLUMN document.number IS \'номер документа\'');
        $this->addSql('COMMENT ON COLUMN document.date IS \'дата выдачи\'');
        $this->addSql('COMMENT ON COLUMN document.sub_code IS \'код подразделения\'');
        $this->addSql('COMMENT ON COLUMN document.given IS \'кем выдан\'');
        $this->addSql('CREATE TABLE education (id SERIAL NOT NULL, name VARCHAR(128) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE email_dispatch (id SERIAL NOT NULL, subject VARCHAR(256) DEFAULT \'\' NOT NULL, body TEXT NOT NULL, source VARCHAR(255) DEFAULT \'html\' NOT NULL, category VARCHAR(255) DEFAULT \'info\' NOT NULL, name VARCHAR(50) DEFAULT \'Рас-рас-рассылка\' NOT NULL, active VARCHAR(255) DEFAULT \'N\' NOT NULL, created_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_actor INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN email_dispatch.created_date IS \'Дата создания\'');
        $this->addSql('CREATE TABLE email_dispatch_done (id SERIAL NOT NULL, actor INT DEFAULT NULL, email_dispatch INT DEFAULT NULL, recipient_code VARCHAR(20000) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, state VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX FK_email_dispatch_done_actor ON email_dispatch_done (actor)');
        $this->addSql('CREATE INDEX FK_email_dispatch_done_email_dispatch ON email_dispatch_done (email_dispatch)');
        $this->addSql('CREATE TABLE email_dispatch_to (id SERIAL NOT NULL, ed_id INT DEFAULT NULL, person_id INT NOT NULL, person_email VARCHAR(200) NOT NULL, body TEXT NOT NULL, sent BOOLEAN DEFAULT \'false\' NOT NULL, unsubscribe_token CHAR(20) DEFAULT \'\' NOT NULL, state VARCHAR(255) DEFAULT \'queued\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX FK_email_dispatch_to_person ON email_dispatch_to (person_id)');
        $this->addSql('CREATE INDEX IDX_B90A1A9ABAB47356 ON email_dispatch_to (ed_id)');
        $this->addSql('CREATE UNIQUE INDEX ed_id_person_email ON email_dispatch_to (ed_id, person_email)');
        $this->addSql('CREATE TABLE email_friends_reference (id SERIAL NOT NULL, person_id INT DEFAULT NULL, email VARCHAR(100) DEFAULT \'0\' NOT NULL, subject VARCHAR(256) DEFAULT \'\' NOT NULL, body TEXT NOT NULL, dt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX email_friends_reference__email ON email_friends_reference (email)');
        $this->addSql('CREATE INDEX email_friends_reference__person_id ON email_friends_reference (person_id)');
        $this->addSql('CREATE TABLE email_out (id SERIAL NOT NULL, from_person INT DEFAULT NULL, to_person INT DEFAULT NULL, dt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, from_email VARCHAR(100) NOT NULL, to_email VARCHAR(100) NOT NULL, subject VARCHAR(100) NOT NULL, body TEXT NOT NULL, type VARCHAR(25) NOT NULL, sended BOOLEAN DEFAULT \'false\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX FK_email_out_to_person ON email_out (to_person)');
        $this->addSql('CREATE INDEX FK_email_out_from_person ON email_out (from_person)');
        $this->addSql('CREATE TABLE event (id SERIAL NOT NULL, club_home INT DEFAULT NULL, club_guest INT DEFAULT NULL, place_id INT DEFAULT NULL, promo_action INT DEFAULT NULL, sport_id INT DEFAULT NULL, name VARCHAR(256) NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, purchasable BOOLEAN DEFAULT \'false\' NOT NULL, chship VARCHAR(255) DEFAULT \'NA\' NOT NULL, score_home BOOLEAN DEFAULT \'false\' NOT NULL, score_guest BOOLEAN DEFAULT \'false\' NOT NULL, score_saved BOOLEAN DEFAULT \'false\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX FK_event_club ON event (club_home)');
        $this->addSql('CREATE INDEX FK_event_club_2 ON event (club_guest)');
        $this->addSql('CREATE INDEX FK_event_place ON event (place_id)');
        $this->addSql('CREATE INDEX FK_event_sport ON event (sport_id)');
        $this->addSql('CREATE INDEX FK_event_promo_action ON event (promo_action)');
        $this->addSql('CREATE INDEX event__date ON event (date)');
        $this->addSql('CREATE TABLE event_attendance (id SERIAL NOT NULL, event_id INT DEFAULT NULL, person_id INT DEFAULT NULL, ticket_id INT DEFAULT NULL, subscription_id INT DEFAULT NULL, fan_card INT DEFAULT NULL, enter_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX FK_event_attendance_event ON event_attendance (event_id)');
        $this->addSql('CREATE INDEX FK_event_attendance_person ON event_attendance (person_id)');
        $this->addSql('CREATE TABLE event_attendance_import (id SERIAL NOT NULL, event_id INT DEFAULT NULL, person_id INT DEFAULT NULL, price SMALLINT DEFAULT 0 NOT NULL, ticket_number BIGINT DEFAULT NULL, subscription_number VARCHAR(20) DEFAULT NULL, fan_card_number VARCHAR(20) DEFAULT NULL, enter_dt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, electronic BOOLEAN DEFAULT \'false\' NOT NULL, place_buy INT DEFAULT 0 NOT NULL, time_buy TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, fio VARCHAR(100) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX event_attendance_import__ticket_number ON event_attendance_import (ticket_number)');
        $this->addSql('CREATE INDEX FK_event_attendance_import_person ON event_attendance_import (person_id)');
        $this->addSql('CREATE INDEX event_id ON event_attendance_import (event_id)');
        $this->addSql('CREATE UNIQUE INDEX event_id_ticket_number ON event_attendance_import (event_id, ticket_number)');
        $this->addSql('CREATE UNIQUE INDEX event_id_subscription_number ON event_attendance_import (event_id, subscription_number)');
        $this->addSql('CREATE TABLE event_attendance_placebuy (id SERIAL NOT NULL, name VARCHAR(100) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE event_attendance_ticket (id SERIAL NOT NULL, person_id INT DEFAULT NULL, mobile CHAR(11) NOT NULL, first_name VARCHAR(256) DEFAULT NULL, last_name VARCHAR(256) DEFAULT NULL, barcode CHAR(13) NOT NULL, dt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, no_process BOOLEAN DEFAULT \'false\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX FK_event_attendance_ticket_person ON event_attendance_ticket (person_id)');
        $this->addSql('CREATE UNIQUE INDEX event_attance_ticket__barcode ON event_attendance_ticket (barcode)');
        $this->addSql('CREATE TABLE event_condition (id SERIAL NOT NULL, event_id INT DEFAULT NULL, temperature BOOLEAN NOT NULL, weather TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX event_condition__event_id ON event_condition (event_id)');
        $this->addSql('CREATE TABLE event_map (id SERIAL NOT NULL, app_id INT DEFAULT NULL, event_id INT DEFAULT NULL, outer_id INT NOT NULL, use4promo BOOLEAN DEFAULT \'false\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX event_map_event ON event_map (event_id)');
        $this->addSql('CREATE INDEX IDX_82626F687987212D ON event_map (app_id)');
        $this->addSql('CREATE UNIQUE INDEX app_id_event_id_outer_id ON event_map (app_id, event_id, outer_id)');
        $this->addSql('CREATE TABLE event_out_spot (id SERIAL NOT NULL, event_id INT DEFAULT NULL, purchase_id INT DEFAULT NULL, code CHAR(10) NOT NULL, reserved BOOLEAN DEFAULT \'false\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX FK_event_out_spot_event ON event_out_spot (event_id)');
        $this->addSql('CREATE INDEX FK_event_out_spot_person_purchase ON event_out_spot (purchase_id)');
        $this->addSql('CREATE TABLE fan_card (id SERIAL NOT NULL, number VARCHAR(50) DEFAULT \'0\' NOT NULL, inner_number VARCHAR(50) DEFAULT \'0\' NOT NULL, state VARCHAR(255) DEFAULT \'Active\' NOT NULL, best_before_date DATE NOT NULL, spent_sum NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL, points NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL, given_date DATE NOT NULL, blocked_reason VARCHAR(255) DEFAULT NULL, blocked_reason_comment VARCHAR(512) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN fan_card.spent_sum IS \'Потрачено денег по этой карте\'');
        $this->addSql('COMMENT ON COLUMN fan_card.points IS \'Начисленные баллы по этой карте\'');
        $this->addSql('CREATE TABLE fan_card_person (fancard_id INT NOT NULL, person_id INT NOT NULL, PRIMARY KEY(fancard_id, person_id))');
        $this->addSql('CREATE INDEX IDX_315BDCD466AA7E71 ON fan_card_person (fancard_id)');
        $this->addSql('CREATE INDEX IDX_315BDCD4217BBB47 ON fan_card_person (person_id)');
        $this->addSql('CREATE TABLE giveaway_action (id SERIAL NOT NULL, actor_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT \'Free zens to everyone\' NOT NULL, occasion VARCHAR(1024) DEFAULT \'\' NOT NULL, dt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, points SMALLINT NOT NULL, progress BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX FK_giveaway_action_actor ON giveaway_action (actor_id)');
        $this->addSql('CREATE INDEX giveaway_action__name ON giveaway_action (name)');
        $this->addSql('CREATE TABLE item (id SERIAL NOT NULL, event_id INT DEFAULT NULL, how2get INT DEFAULT NULL, active BOOLEAN DEFAULT \'false\' NOT NULL, parent_item INT DEFAULT NULL, rule INT DEFAULT NULL, outer_id INT NOT NULL, app_id INT NOT NULL, price_points VARCHAR(50) DEFAULT \'0\' NOT NULL, price_rub VARCHAR(50) DEFAULT \'0\' NOT NULL, name VARCHAR(256) DEFAULT \'Приз\' NOT NULL, img VARCHAR(1024) DEFAULT \'/static/img/prize1.png\' NOT NULL, sortorder BOOLEAN DEFAULT \'false\', PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX FK_item_item_how2get ON item (how2get)');
        $this->addSql('CREATE INDEX FK_item_event ON item (event_id)');
        $this->addSql('CREATE INDEX item__sortorder_ix ON item (sortorder)');
        $this->addSql('COMMENT ON COLUMN item.app_id IS \'ид внешнего приложения\'');
        $this->addSql('COMMENT ON COLUMN item.price_points IS \'цена в баллах\'');
        $this->addSql('COMMENT ON COLUMN item.price_rub IS \'цена в рублях\'');
        $this->addSql('CREATE TABLE item_how2get (id SERIAL NOT NULL, name VARCHAR(128) DEFAULT \'\' NOT NULL, display_text TEXT DEFAULT NULL, purchase_text TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE line_of_work (id SERIAL NOT NULL, name VARCHAR(256) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE log_callcenter (id SERIAL NOT NULL, actor_id INT DEFAULT 0 NOT NULL, person_id INT DEFAULT 0 NOT NULL, dt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, old TEXT NOT NULL, new TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE news (id SERIAL NOT NULL, text TEXT NOT NULL, hide BOOLEAN NOT NULL, dt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, dt_start TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, dt_end TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actor_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX news__date__indx ON news (dt_start, dt_end)');
        $this->addSql('CREATE TABLE person (id SERIAL NOT NULL, city INT DEFAULT NULL, club_owner INT DEFAULT NULL, district INT DEFAULT NULL, education INT DEFAULT NULL, line_of_work INT DEFAULT NULL, promo_code VARCHAR(20) DEFAULT NULL, avatar TEXT DEFAULT NULL, first_name VARCHAR(256) DEFAULT NULL, last_name VARCHAR(256) DEFAULT NULL, middle_name VARCHAR(256) DEFAULT NULL, sex VARCHAR(255) DEFAULT NULL, familystatus VARCHAR(255) DEFAULT NULL, bdate DATE DEFAULT NULL, comes_by VARCHAR(255) DEFAULT NULL, address VARCHAR(256) DEFAULT NULL, mobile VARCHAR(50) DEFAULT NULL, mobile_available VARCHAR(255) DEFAULT NULL, email VARCHAR(100) DEFAULT NULL, mobile_add VARCHAR(50) DEFAULT NULL, email_add VARCHAR(100) DEFAULT NULL, notes TEXT DEFAULT NULL, work_at VARCHAR(256) DEFAULT \'\' NOT NULL, study_at VARCHAR(256) DEFAULT \'\' NOT NULL, email_allowed BOOLEAN DEFAULT \'true\' NOT NULL, sms_allowed BOOLEAN DEFAULT \'true\' NOT NULL, reg_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, reg_actor INT DEFAULT NULL, reg_type VARCHAR(255) DEFAULT \'other\', reg_type_name VARCHAR(256) DEFAULT NULL, email_confirmed BOOLEAN DEFAULT \'false\' NOT NULL, events_info TEXT DEFAULT \'\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX FK_person_line_of_work ON person (line_of_work)');
        $this->addSql('CREATE INDEX FK_person_education ON person (education)');
        $this->addSql('CREATE INDEX FK_person_city ON person (city)');
        $this->addSql('CREATE INDEX FK_person_district ON person (district)');
        $this->addSql('CREATE INDEX person__email ON person (email)');
        $this->addSql('CREATE INDEX person__club ON person (club_owner)');
        $this->addSql('CREATE INDEX person__reg_type_name ON person (reg_type_name)');
        $this->addSql('CREATE UNIQUE INDEX person__promo_code ON person (promo_code)');
        $this->addSql('CREATE UNIQUE INDEX person__club_owner_mobile ON person (club_owner, mobile)');
        $this->addSql('COMMENT ON COLUMN person.work_at IS \'место работы\'');
        $this->addSql('COMMENT ON COLUMN person.study_at IS \'место учёбы\'');
        $this->addSql('COMMENT ON COLUMN person.events_info IS \'(DC2Type:simple_array)\'');
        $this->addSql('CREATE TABLE person_activity (person_id INT NOT NULL, activity_id INT NOT NULL, PRIMARY KEY(person_id, activity_id))');
        $this->addSql('CREATE INDEX IDX_3832AC6D217BBB47 ON person_activity (person_id)');
        $this->addSql('CREATE INDEX IDX_3832AC6D81C06096 ON person_activity (activity_id)');
        $this->addSql('CREATE TABLE video_view (person_id INT NOT NULL, video_id INT NOT NULL, PRIMARY KEY(person_id, video_id))');
        $this->addSql('CREATE INDEX IDX_F96AF652217BBB47 ON video_view (person_id)');
        $this->addSql('CREATE INDEX IDX_F96AF65229C1004E ON video_view (video_id)');
        $this->addSql('CREATE TABLE person_event_forecast (id SERIAL NOT NULL, event_id INT DEFAULT NULL, person_id INT DEFAULT NULL, score_home INT NOT NULL, score_guest INT NOT NULL, dt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX FK_person_event_forecast_event ON person_event_forecast (event_id)');
        $this->addSql('CREATE INDEX person_event_forecast__dt ON person_event_forecast (dt)');
        $this->addSql('CREATE INDEX IDX_89ADA1AA217BBB47 ON person_event_forecast (person_id)');
        $this->addSql('CREATE UNIQUE INDEX person_event ON person_event_forecast (person_id, event_id)');
        $this->addSql('CREATE TABLE person_points (id SERIAL NOT NULL, season_id INT DEFAULT NULL, person_id INT DEFAULT NULL, points SMALLINT DEFAULT 0 NOT NULL, type VARCHAR(255) NOT NULL, state VARCHAR(255) DEFAULT \'none\' NOT NULL, dt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX person_points__person_id ON person_points (person_id)');
        $this->addSql('CREATE INDEX person_points__type ON person_points (type)');
        $this->addSql('CREATE INDEX person_points__season_id ON person_points (season_id)');
        $this->addSql('CREATE TABLE person_progress (person_id INT NOT NULL, progress_id INT DEFAULT NULL, dt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(person_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B647577143DB87C9 ON person_progress (progress_id)');
        $this->addSql('CREATE INDEX FK_person_progress_progress_items ON person_progress (progress_id)');
        $this->addSql('CREATE UNIQUE INDEX person_id_progress_item_id ON person_progress (person_id, progress_id)');
        $this->addSql('CREATE TABLE person_purchase (id SERIAL NOT NULL, item_id INT DEFAULT NULL, how2get INT DEFAULT NULL, person_id INT DEFAULT NULL, app_id INT NOT NULL, price_points VARCHAR(50) NOT NULL, url_called VARCHAR(255) NOT NULL, query_string VARCHAR(255) NOT NULL, checksum VARCHAR(50) NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status BOOLEAN NOT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ship_to VARCHAR(300) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX FK_person_purchase_item ON person_purchase (item_id)');
        $this->addSql('CREATE INDEX FK_person_purchase_person ON person_purchase (person_id)');
        $this->addSql('CREATE INDEX FK_person_purchase_item_how2get ON person_purchase (how2get)');
        $this->addSql('CREATE TABLE person_subs (person_id INT NOT NULL, list_id INT NOT NULL, enabled BOOLEAN NOT NULL, PRIMARY KEY(person_id, list_id))');
        $this->addSql('CREATE TABLE place (id SERIAL NOT NULL, name VARCHAR(256) NOT NULL, country INT DEFAULT 1 NOT NULL, city INT DEFAULT 1 NOT NULL, street VARCHAR(256) NOT NULL, number VARCHAR(256) NOT NULL, description VARCHAR(1024) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN place.number IS \'номер строения\'');
        $this->addSql('CREATE TABLE player (id SERIAL NOT NULL, club INT DEFAULT NULL, name VARCHAR(200) DEFAULT \'нет\' NOT NULL, active BOOLEAN DEFAULT \'false\' NOT NULL, bdate DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX FK_player_club ON player (club)');
        $this->addSql('COMMENT ON COLUMN player.bdate IS \'Дата рождения игрока\'');
        $this->addSql('CREATE TABLE points_status (id SERIAL NOT NULL, points SMALLINT DEFAULT 0 NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX point_status__points ON points_status (points, title)');
        $this->addSql('CREATE TABLE progress_items (id SERIAL NOT NULL, progress_class CHAR(50) NOT NULL, progress_key CHAR(50) NOT NULL, title VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE promo_action (id SERIAL NOT NULL, club_owner INT DEFAULT NULL, name VARCHAR(256) NOT NULL, displayname VARCHAR(1024) NOT NULL, active BOOLEAN DEFAULT \'false\' NOT NULL, dt_start DATE DEFAULT NULL, dt_end DATE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX promo_action__club ON promo_action (club_owner)');
        $this->addSql('CREATE TABLE promo_code (id SERIAL NOT NULL, action INT DEFAULT NULL, sms INT DEFAULT NULL, ticket INT DEFAULT NULL, code VARCHAR(10) DEFAULT NULL, used INT DEFAULT 0 NOT NULL, electronic BOOLEAN DEFAULT \'false\' NOT NULL, email INT DEFAULT NULL, barcode BIGINT DEFAULT NULL, outer_id INT DEFAULT NULL, activated_dt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX promo_code__promo_action ON promo_code (action)');
        $this->addSql('CREATE INDEX promo_code__ticket ON promo_code (ticket)');
        $this->addSql('CREATE INDEX promo_code__barcode ON promo_code (barcode)');
        $this->addSql('CREATE INDEX promo_code__email ON promo_code (email)');
        $this->addSql('CREATE UNIQUE INDEX code_ticket ON promo_code (code, ticket)');
        $this->addSql('CREATE UNIQUE INDEX sms ON promo_code (sms)');
        $this->addSql('CREATE TABLE promo_code_distribution (id SERIAL NOT NULL, event_id INT DEFAULT NULL, promo_action_id INT DEFAULT NULL, area_id INT DEFAULT NULL, number_start VARCHAR(50) NOT NULL, number_end VARCHAR(50) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX promo_code_distribution__promo_action_id ON promo_code_distribution (promo_action_id)');
        $this->addSql('CREATE INDEX promo_code_distribution__number_start ON promo_code_distribution (number_start)');
        $this->addSql('CREATE INDEX promo_code_distribution__number_end ON promo_code_distribution (number_end)');
        $this->addSql('CREATE INDEX promo_code_distribution__area_id ON promo_code_distribution (area_id)');
        $this->addSql('CREATE INDEX promo_code_distribution__event_id ON promo_code_distribution (event_id)');
        $this->addSql('CREATE UNIQUE INDEX event_id_number_start_number_end ON promo_code_distribution (event_id, number_start, number_end)');
        $this->addSql('CREATE TABLE promo_code_distribution_area (id SERIAL NOT NULL, name VARCHAR(256) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE promo_coupon (id SERIAL NOT NULL, pcaction INT DEFAULT NULL, code VARCHAR(255) NOT NULL, points SMALLINT NOT NULL, activated BOOLEAN DEFAULT \'false\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX FK_promo_coupon_promo_coupon_action ON promo_coupon (pcaction)');
        $this->addSql('CREATE UNIQUE INDEX code ON promo_coupon (code)');
        $this->addSql('CREATE TABLE promo_coupon_action (id SERIAL NOT NULL, club_owner INT DEFAULT NULL, caption VARCHAR(256) NOT NULL, end_dt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_blocked BOOLEAN DEFAULT \'false\' NOT NULL, pca_type VARCHAR(255) DEFAULT \'normal\' NOT NULL, allowed_days BOOLEAN DEFAULT \'false\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX FK_promo_coupon_action_club ON promo_coupon_action (club_owner)');
        $this->addSql('CREATE TABLE promo_email_in (id SERIAL NOT NULL, person INT DEFAULT NULL, email VARCHAR(128) DEFAULT \'0\' NOT NULL, token VARCHAR(50) DEFAULT \'\'\'\' NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, content TEXT NOT NULL, special VARCHAR(255) DEFAULT \'NONE\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX promo_email_in__email ON promo_email_in (email)');
        $this->addSql('CREATE INDEX promo_email_in__token ON promo_email_in (token)');
        $this->addSql('CREATE INDEX promo_email_in__person ON promo_email_in (person)');
        $this->addSql('CREATE TABLE promo_sms_in (id SERIAL NOT NULL, person_id INT DEFAULT NULL, frommobile VARCHAR(32) NOT NULL, tomobile VARCHAR(32) NOT NULL, outerid VARCHAR(32) NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, prefix VARCHAR(32) NOT NULL, content VARCHAR(256) NOT NULL, special VARCHAR(255) DEFAULT \'NONE\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX promo_sms_in__frommobile ON promo_sms_in (frommobile)');
        $this->addSql('CREATE INDEX promo_sms_in__person_id ON promo_sms_in (person_id)');
        $this->addSql('CREATE TABLE promo_sms_out (id SERIAL NOT NULL, tomobile VARCHAR(32) NOT NULL, person_id INT NOT NULL, queued_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sent_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, content VARCHAR(256) NOT NULL, sent BOOLEAN DEFAULT \'false\' NOT NULL, sms_in INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE push_device_id (os VARCHAR(255) NOT NULL, person_id INT DEFAULT NULL, device_id TEXT NOT NULL, PRIMARY KEY(os))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1F7E2FD3217BBB47 ON push_device_id (person_id)');
        $this->addSql('CREATE INDEX FK_push_device_id_person ON push_device_id (person_id)');
        $this->addSql('CREATE TABLE role (id SERIAL NOT NULL, role VARCHAR(50) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE role_actor (role_id INT NOT NULL, actor_id INT NOT NULL, PRIMARY KEY(role_id, actor_id))');
        $this->addSql('CREATE INDEX IDX_B3A9BED6D60322AC ON role_actor (role_id)');
        $this->addSql('CREATE INDEX IDX_B3A9BED610DAF24A ON role_actor (actor_id)');
        $this->addSql('CREATE TABLE security (id SERIAL NOT NULL, person_id INT DEFAULT 0 NOT NULL, type INT DEFAULT 0 NOT NULL, offence_count INT DEFAULT 0 NOT NULL, comment VARCHAR(1024) DEFAULT \'0\', PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX FK_security_person ON security (person_id)');
        $this->addSql('CREATE TABLE sms_out (id SERIAL NOT NULL, from_mobile VARCHAR(11) NOT NULL, to_mobile VARCHAR(11) NOT NULL, person_id INT DEFAULT NULL, dt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, text VARCHAR(512) NOT NULL, type VARCHAR(32) NOT NULL, number_sms SMALLINT DEFAULT 0 NOT NULL, outer_id VARCHAR(50) DEFAULT \'\' NOT NULL, status VARCHAR(128) DEFAULT \'\' NOT NULL, sms_in INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX sms_out__to_mobile ON sms_out (to_mobile)');
        $this->addSql('CREATE TABLE social_account (id SERIAL NOT NULL, person_id INT DEFAULT NULL, network VARCHAR(255) NOT NULL, group_id VARCHAR(20) DEFAULT NULL, club_id INT DEFAULT NULL, outer_id VARCHAR(255) NOT NULL, deleted BOOLEAN DEFAULT \'false\' NOT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, sex VARCHAR(255) DEFAULT NULL, bdate DATE DEFAULT NULL, country INT DEFAULT NULL, city VARCHAR(50) DEFAULT NULL, mobile_phone VARCHAR(50) DEFAULT NULL, home_phone VARCHAR(50) DEFAULT NULL, photo TEXT DEFAULT NULL, access_token VARCHAR(256) DEFAULT NULL, link VARCHAR(256) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX social_account__person ON social_account (person_id)');
        $this->addSql('CREATE INDEX social_account__sex ON social_account (sex)');
        $this->addSql('CREATE INDEX social_account__bdate ON social_account (bdate)');
        $this->addSql('CREATE INDEX social_account__country ON social_account (country)');
        $this->addSql('CREATE INDEX social_account__city ON social_account (city)');
        $this->addSql('CREATE INDEX social_account__mobile_phone ON social_account (mobile_phone)');
        $this->addSql('CREATE INDEX social_account__home_phone ON social_account (home_phone)');
        $this->addSql('CREATE INDEX social_account__club_id ON social_account (club_id)');
        $this->addSql('CREATE UNIQUE INDEX network_group_id_club_id_outer_id ON social_account (network, group_id, club_id, outer_id)');
        $this->addSql('CREATE UNIQUE INDEX network_club_person_outerid ON social_account (network, club_id, person_id, outer_id)');
        $this->addSql('CREATE TABLE social_post (id SERIAL NOT NULL, club_id INT DEFAULT 0 NOT NULL, network VARCHAR(255) NOT NULL, group_id VARCHAR(50) DEFAULT \'\' NOT NULL, outerid VARCHAR(50) DEFAULT \'\' NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, text TEXT DEFAULT NULL, textbig TEXT DEFAULT NULL, link TEXT DEFAULT NULL, pic TEXT DEFAULT NULL, picbig TEXT DEFAULT NULL, reposts INT DEFAULT 0 NOT NULL, likes INT DEFAULT 0 NOT NULL, comments INT DEFAULT 0 NOT NULL, views INT DEFAULT 0 NOT NULL, moder BOOLEAN DEFAULT \'false\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX social_post__moder ON social_post (moder)');
        $this->addSql('CREATE INDEX social_post__group_id ON social_post (group_id)');
        $this->addSql('CREATE INDEX social_post__likes ON social_post (likes)');
        $this->addSql('CREATE INDEX social_post__views ON social_post (views)');
        $this->addSql('CREATE INDEX social_post__club_id ON social_post (club_id)');
        $this->addSql('CREATE INDEX social_post__date ON social_post (date)');
        $this->addSql('CREATE INDEX social_post__network ON social_post (network)');
        $this->addSql('CREATE UNIQUE INDEX network_group_id_outerid ON social_post (network, group_id, outerid)');
        $this->addSql('COMMENT ON COLUMN social_post.moder IS \'статус модерации\'');
        $this->addSql('CREATE TABLE social_post_attachments (id SERIAL NOT NULL, post_id INT DEFAULT NULL, type VARCHAR(255) DEFAULT \'video\' NOT NULL, outer_id VARCHAR(50) DEFAULT NULL, inner_link VARCHAR(256) DEFAULT NULL, outer_link VARCHAR(256) DEFAULT NULL, pic_small VARCHAR(100) DEFAULT NULL, pic_big VARCHAR(100) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX FK_social_post_attachments_social_post ON social_post_attachments (post_id)');
        $this->addSql('CREATE UNIQUE INDEX post_id_outer_id ON social_post_attachments (post_id, outer_id)');
        $this->addSql('CREATE TABLE social_repost (id SERIAL NOT NULL, person_id INT DEFAULT NULL, post_id INT DEFAULT NULL, network VARCHAR(255) NOT NULL, user_outerid VARCHAR(50) NOT NULL, repost_outerid VARCHAR(50) NOT NULL, repost_dt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX FK_social_repost_person ON social_repost (person_id)');
        $this->addSql('CREATE INDEX IDX_C37F24194B89032C ON social_repost (post_id)');
        $this->addSql('CREATE UNIQUE INDEX post_id_user_outerid ON social_repost (post_id, user_outerid)');
        $this->addSql('COMMENT ON COLUMN social_repost.repost_dt IS \'Дата репоста\'');
        $this->addSql('CREATE TABLE social_token (id SERIAL NOT NULL, network VARCHAR(255) NOT NULL, user_outer_id VARCHAR(64) DEFAULT \'\' NOT NULL, token VARCHAR(512) DEFAULT \'\' NOT NULL, permissions VARCHAR(1024) DEFAULT \'\' NOT NULL, secret VARCHAR(256) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE sport (id SERIAL NOT NULL, name VARCHAR(100) DEFAULT \'0\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX sport__name__unique ON sport (name)');
        $this->addSql('CREATE TABLE sportomat (id SERIAL NOT NULL, email VARCHAR(50) DEFAULT NULL, fname VARCHAR(50) DEFAULT NULL, lname VARCHAR(50) DEFAULT NULL, testresult TEXT DEFAULT NULL, favsport VARCHAR(256) DEFAULT NULL, dt TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE subscription (id SERIAL NOT NULL, fan_card_id INT DEFAULT NULL, person_id INT DEFAULT NULL, season INT DEFAULT NULL, mifare VARCHAR(20) NOT NULL, serial VARCHAR(10) DEFAULT NULL, number VARCHAR(50) NOT NULL, stand VARCHAR(50) DEFAULT NULL, sector VARCHAR(50) NOT NULL, row VARCHAR(50) NOT NULL, seat VARCHAR(50) NOT NULL, price VARCHAR(50) NOT NULL, note VARCHAR(512) DEFAULT \'\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX FK_subscription_fan_card ON subscription (fan_card_id)');
        $this->addSql('CREATE INDEX FK_subscription_person ON subscription (person_id)');
        $this->addSql('CREATE INDEX FK_subscription_promo_action ON subscription (season)');
        $this->addSql('CREATE UNIQUE INDEX subscription__stand_sector_row_seat ON subscription (stand, sector, row, seat)');
        $this->addSql('CREATE UNIQUE INDEX subscription__serial_number ON subscription (serial, number)');
        $this->addSql('CREATE UNIQUE INDEX subscription__person_id_fan_card_id ON subscription (person_id, fan_card_id)');
        $this->addSql('CREATE TABLE subs_list (id SERIAL NOT NULL, name VARCHAR(256) DEFAULT \'\' NOT NULL, outer_id VARCHAR(256) DEFAULT \'\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE ticket (id SERIAL NOT NULL, event_id INT DEFAULT NULL, person_id INT DEFAULT NULL, fan_card_id INT DEFAULT NULL, serial VARCHAR(10) DEFAULT \'\' NOT NULL, number BIGINT NOT NULL, stand VARCHAR(50) DEFAULT \'\' NOT NULL, sector VARCHAR(50) DEFAULT \'\' NOT NULL, row VARCHAR(50) DEFAULT \'\' NOT NULL, seat VARCHAR(50) NOT NULL, price DOUBLE PRECISION DEFAULT \'0\' NOT NULL, state VARCHAR(255) DEFAULT \'idle\' NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX ticket__event ON ticket (event_id)');
        $this->addSql('CREATE INDEX ticket__fan_card ON ticket (fan_card_id)');
        $this->addSql('CREATE INDEX ticket__state ON ticket (state)');
        $this->addSql('CREATE INDEX ticket__number ON ticket (number)');
        $this->addSql('CREATE INDEX ticket__person_id ON ticket (person_id)');
        $this->addSql('CREATE UNIQUE INDEX ticket__stand_sector_row_seat ON ticket (event_id, stand, sector, row, seat)');
        $this->addSql('CREATE UNIQUE INDEX ticket__event_id_number ON ticket (event_id, number)');
        $this->addSql('CREATE UNIQUE INDEX ticket__event_id_by_person ON ticket (person_id, event_id, number)');
        $this->addSql('CREATE TABLE video (id SERIAL NOT NULL, name VARCHAR(50) NOT NULL, depiction VARCHAR(250) NOT NULL, file VARCHAR(250) NOT NULL, img VARCHAR(250) DEFAULT \'/static/img/video.jpg\' NOT NULL, view_cond VARCHAR(255) NOT NULL, dt TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, actor_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX name ON video (name)');
        $this->addSql('ALTER TABLE actor ADD CONSTRAINT FK_447556F96F0ECCCE FOREIGN KEY (club_owner) REFERENCES club (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE actor ADD CONSTRAINT FK_447556F934DCD176 FOREIGN KEY (person) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE auth_log ADD CONSTRAINT FK_1DD25DB8217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE client_application ADD CONSTRAINT FK_A510F8FA6F0ECCCE FOREIGN KEY (club_owner) REFERENCES club (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE club ADD CONSTRAINT FK_B8EE38721A85EFD2 FOREIGN KEY (sport) REFERENCES sport (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE email_dispatch_done ADD CONSTRAINT FK_A1AAB47E447556F9 FOREIGN KEY (actor) REFERENCES actor (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE email_dispatch_done ADD CONSTRAINT FK_A1AAB47E8D747913 FOREIGN KEY (email_dispatch) REFERENCES email_dispatch (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE email_dispatch_to ADD CONSTRAINT FK_B90A1A9ABAB47356 FOREIGN KEY (ed_id) REFERENCES email_dispatch_done (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE email_friends_reference ADD CONSTRAINT FK_94F51EDD217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE email_out ADD CONSTRAINT FK_302E4DDFB9EDAAA6 FOREIGN KEY (from_person) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE email_out ADD CONSTRAINT FK_302E4DDF120EDDEB FOREIGN KEY (to_person) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7151EC630 FOREIGN KEY (club_home) REFERENCES club (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7CD9B087 FOREIGN KEY (club_guest) REFERENCES club (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7DA6A219 FOREIGN KEY (place_id) REFERENCES place (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA75E4993DF FOREIGN KEY (promo_action) REFERENCES promo_action (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT FK_3BAE0AA7AC78BCF8 FOREIGN KEY (sport_id) REFERENCES sport (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_attendance ADD CONSTRAINT FK_350DD4BE71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_attendance ADD CONSTRAINT FK_350DD4BE217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_attendance_import ADD CONSTRAINT FK_A2FD8F7871F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_attendance_import ADD CONSTRAINT FK_A2FD8F78217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_attendance_ticket ADD CONSTRAINT FK_A813ECC6217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_condition ADD CONSTRAINT FK_3B43B67E71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_map ADD CONSTRAINT FK_82626F687987212D FOREIGN KEY (app_id) REFERENCES client_application (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_map ADD CONSTRAINT FK_82626F6871F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_out_spot ADD CONSTRAINT FK_26D3C98071F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE event_out_spot ADD CONSTRAINT FK_26D3C980558FBEB9 FOREIGN KEY (purchase_id) REFERENCES person_purchase (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fan_card_person ADD CONSTRAINT FK_315BDCD466AA7E71 FOREIGN KEY (fancard_id) REFERENCES fan_card (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE fan_card_person ADD CONSTRAINT FK_315BDCD4217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE giveaway_action ADD CONSTRAINT FK_D8DCFD1C10DAF24A FOREIGN KEY (actor_id) REFERENCES actor (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251E71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251ECF3D9BE4 FOREIGN KEY (how2get) REFERENCES item_how2get (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD1762D5B0234 FOREIGN KEY (city) REFERENCES city (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD1766F0ECCCE FOREIGN KEY (club_owner) REFERENCES club (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD17631C15487 FOREIGN KEY (district) REFERENCES district (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD176DB0A5ED2 FOREIGN KEY (education) REFERENCES education (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD17643D261D4 FOREIGN KEY (line_of_work) REFERENCES line_of_work (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_activity ADD CONSTRAINT FK_3832AC6D217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_activity ADD CONSTRAINT FK_3832AC6D81C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_view ADD CONSTRAINT FK_F96AF652217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE video_view ADD CONSTRAINT FK_F96AF65229C1004E FOREIGN KEY (video_id) REFERENCES video (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_event_forecast ADD CONSTRAINT FK_89ADA1AA71F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_event_forecast ADD CONSTRAINT FK_89ADA1AA217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_points ADD CONSTRAINT FK_BB1FBE9F4EC001D1 FOREIGN KEY (season_id) REFERENCES promo_action (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_points ADD CONSTRAINT FK_BB1FBE9F217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_progress ADD CONSTRAINT FK_B647577143DB87C9 FOREIGN KEY (progress_id) REFERENCES progress_items (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_purchase ADD CONSTRAINT FK_F551740C126F525E FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_purchase ADD CONSTRAINT FK_F551740CCF3D9BE4 FOREIGN KEY (how2get) REFERENCES item_how2get (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE person_purchase ADD CONSTRAINT FK_F551740C217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A65B8EE3872 FOREIGN KEY (club) REFERENCES club (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE promo_action ADD CONSTRAINT FK_5E4993DF6F0ECCCE FOREIGN KEY (club_owner) REFERENCES club (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE promo_code ADD CONSTRAINT FK_3D8C939E47CC8C92 FOREIGN KEY (action) REFERENCES promo_action (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE promo_code ADD CONSTRAINT FK_3D8C939EB0A93A77 FOREIGN KEY (sms) REFERENCES promo_sms_in (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE promo_code ADD CONSTRAINT FK_3D8C939E97A0ADA3 FOREIGN KEY (ticket) REFERENCES ticket (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE promo_code_distribution ADD CONSTRAINT FK_EB2F246971F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE promo_code_distribution ADD CONSTRAINT FK_EB2F2469B5F8978E FOREIGN KEY (promo_action_id) REFERENCES promo_action (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE promo_code_distribution ADD CONSTRAINT FK_EB2F2469BD0F409C FOREIGN KEY (area_id) REFERENCES promo_code_distribution_area (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE promo_coupon ADD CONSTRAINT FK_7D3A204F852235B0 FOREIGN KEY (pcaction) REFERENCES promo_coupon_action (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE promo_coupon_action ADD CONSTRAINT FK_79D4B3D16F0ECCCE FOREIGN KEY (club_owner) REFERENCES club (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE promo_email_in ADD CONSTRAINT FK_80380DEF34DCD176 FOREIGN KEY (person) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE promo_sms_in ADD CONSTRAINT FK_440C8833217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE push_device_id ADD CONSTRAINT FK_1F7E2FD3217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_actor ADD CONSTRAINT FK_B3A9BED6D60322AC FOREIGN KEY (role_id) REFERENCES role (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE role_actor ADD CONSTRAINT FK_B3A9BED610DAF24A FOREIGN KEY (actor_id) REFERENCES actor (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE social_account ADD CONSTRAINT FK_F24D8339217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE social_post_attachments ADD CONSTRAINT FK_DF2A8F344B89032C FOREIGN KEY (post_id) REFERENCES social_post (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE social_repost ADD CONSTRAINT FK_C37F2419217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE social_repost ADD CONSTRAINT FK_C37F24194B89032C FOREIGN KEY (post_id) REFERENCES social_post (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D322C47CDB FOREIGN KEY (fan_card_id) REFERENCES fan_card (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D3217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE subscription ADD CONSTRAINT FK_A3C664D3F0E45BA9 FOREIGN KEY (season) REFERENCES promo_action (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA371F7E88B FOREIGN KEY (event_id) REFERENCES event (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE person_activity DROP CONSTRAINT FK_3832AC6D81C06096');
        $this->addSql('ALTER TABLE email_dispatch_done DROP CONSTRAINT FK_A1AAB47E447556F9');
        $this->addSql('ALTER TABLE giveaway_action DROP CONSTRAINT FK_D8DCFD1C10DAF24A');
        $this->addSql('ALTER TABLE role_actor DROP CONSTRAINT FK_B3A9BED610DAF24A');
        $this->addSql('ALTER TABLE person DROP CONSTRAINT FK_34DCD1762D5B0234');
        $this->addSql('ALTER TABLE event_map DROP CONSTRAINT FK_82626F687987212D');
        $this->addSql('ALTER TABLE actor DROP CONSTRAINT FK_447556F96F0ECCCE');
        $this->addSql('ALTER TABLE client_application DROP CONSTRAINT FK_A510F8FA6F0ECCCE');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA7151EC630');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA7CD9B087');
        $this->addSql('ALTER TABLE person DROP CONSTRAINT FK_34DCD1766F0ECCCE');
        $this->addSql('ALTER TABLE player DROP CONSTRAINT FK_98197A65B8EE3872');
        $this->addSql('ALTER TABLE promo_action DROP CONSTRAINT FK_5E4993DF6F0ECCCE');
        $this->addSql('ALTER TABLE promo_coupon_action DROP CONSTRAINT FK_79D4B3D16F0ECCCE');
        $this->addSql('ALTER TABLE person DROP CONSTRAINT FK_34DCD17631C15487');
        $this->addSql('ALTER TABLE person DROP CONSTRAINT FK_34DCD176DB0A5ED2');
        $this->addSql('ALTER TABLE email_dispatch_done DROP CONSTRAINT FK_A1AAB47E8D747913');
        $this->addSql('ALTER TABLE email_dispatch_to DROP CONSTRAINT FK_B90A1A9ABAB47356');
        $this->addSql('ALTER TABLE event_attendance DROP CONSTRAINT FK_350DD4BE71F7E88B');
        $this->addSql('ALTER TABLE event_attendance_import DROP CONSTRAINT FK_A2FD8F7871F7E88B');
        $this->addSql('ALTER TABLE event_condition DROP CONSTRAINT FK_3B43B67E71F7E88B');
        $this->addSql('ALTER TABLE event_map DROP CONSTRAINT FK_82626F6871F7E88B');
        $this->addSql('ALTER TABLE event_out_spot DROP CONSTRAINT FK_26D3C98071F7E88B');
        $this->addSql('ALTER TABLE item DROP CONSTRAINT FK_1F1B251E71F7E88B');
        $this->addSql('ALTER TABLE person_event_forecast DROP CONSTRAINT FK_89ADA1AA71F7E88B');
        $this->addSql('ALTER TABLE promo_code_distribution DROP CONSTRAINT FK_EB2F246971F7E88B');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA371F7E88B');
        $this->addSql('ALTER TABLE fan_card_person DROP CONSTRAINT FK_315BDCD466AA7E71');
        $this->addSql('ALTER TABLE subscription DROP CONSTRAINT FK_A3C664D322C47CDB');
        $this->addSql('ALTER TABLE person_purchase DROP CONSTRAINT FK_F551740C126F525E');
        $this->addSql('ALTER TABLE item DROP CONSTRAINT FK_1F1B251ECF3D9BE4');
        $this->addSql('ALTER TABLE person_purchase DROP CONSTRAINT FK_F551740CCF3D9BE4');
        $this->addSql('ALTER TABLE person DROP CONSTRAINT FK_34DCD17643D261D4');
        $this->addSql('ALTER TABLE actor DROP CONSTRAINT FK_447556F934DCD176');
        $this->addSql('ALTER TABLE auth_log DROP CONSTRAINT FK_1DD25DB8217BBB47');
        $this->addSql('ALTER TABLE email_friends_reference DROP CONSTRAINT FK_94F51EDD217BBB47');
        $this->addSql('ALTER TABLE email_out DROP CONSTRAINT FK_302E4DDFB9EDAAA6');
        $this->addSql('ALTER TABLE email_out DROP CONSTRAINT FK_302E4DDF120EDDEB');
        $this->addSql('ALTER TABLE event_attendance DROP CONSTRAINT FK_350DD4BE217BBB47');
        $this->addSql('ALTER TABLE event_attendance_import DROP CONSTRAINT FK_A2FD8F78217BBB47');
        $this->addSql('ALTER TABLE event_attendance_ticket DROP CONSTRAINT FK_A813ECC6217BBB47');
        $this->addSql('ALTER TABLE fan_card_person DROP CONSTRAINT FK_315BDCD4217BBB47');
        $this->addSql('ALTER TABLE person_activity DROP CONSTRAINT FK_3832AC6D217BBB47');
        $this->addSql('ALTER TABLE video_view DROP CONSTRAINT FK_F96AF652217BBB47');
        $this->addSql('ALTER TABLE person_event_forecast DROP CONSTRAINT FK_89ADA1AA217BBB47');
        $this->addSql('ALTER TABLE person_points DROP CONSTRAINT FK_BB1FBE9F217BBB47');
        $this->addSql('ALTER TABLE person_purchase DROP CONSTRAINT FK_F551740C217BBB47');
        $this->addSql('ALTER TABLE promo_email_in DROP CONSTRAINT FK_80380DEF34DCD176');
        $this->addSql('ALTER TABLE promo_sms_in DROP CONSTRAINT FK_440C8833217BBB47');
        $this->addSql('ALTER TABLE push_device_id DROP CONSTRAINT FK_1F7E2FD3217BBB47');
        $this->addSql('ALTER TABLE social_account DROP CONSTRAINT FK_F24D8339217BBB47');
        $this->addSql('ALTER TABLE social_repost DROP CONSTRAINT FK_C37F2419217BBB47');
        $this->addSql('ALTER TABLE subscription DROP CONSTRAINT FK_A3C664D3217BBB47');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA3217BBB47');
        $this->addSql('ALTER TABLE event_out_spot DROP CONSTRAINT FK_26D3C980558FBEB9');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA7DA6A219');
        $this->addSql('ALTER TABLE person_progress DROP CONSTRAINT FK_B647577143DB87C9');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA75E4993DF');
        $this->addSql('ALTER TABLE person_points DROP CONSTRAINT FK_BB1FBE9F4EC001D1');
        $this->addSql('ALTER TABLE promo_code DROP CONSTRAINT FK_3D8C939E47CC8C92');
        $this->addSql('ALTER TABLE promo_code_distribution DROP CONSTRAINT FK_EB2F2469B5F8978E');
        $this->addSql('ALTER TABLE subscription DROP CONSTRAINT FK_A3C664D3F0E45BA9');
        $this->addSql('ALTER TABLE promo_code_distribution DROP CONSTRAINT FK_EB2F2469BD0F409C');
        $this->addSql('ALTER TABLE promo_coupon DROP CONSTRAINT FK_7D3A204F852235B0');
        $this->addSql('ALTER TABLE promo_code DROP CONSTRAINT FK_3D8C939EB0A93A77');
        $this->addSql('ALTER TABLE role_actor DROP CONSTRAINT FK_B3A9BED6D60322AC');
        $this->addSql('ALTER TABLE social_post_attachments DROP CONSTRAINT FK_DF2A8F344B89032C');
        $this->addSql('ALTER TABLE social_repost DROP CONSTRAINT FK_C37F24194B89032C');
        $this->addSql('ALTER TABLE club DROP CONSTRAINT FK_B8EE38721A85EFD2');
        $this->addSql('ALTER TABLE event DROP CONSTRAINT FK_3BAE0AA7AC78BCF8');
        $this->addSql('ALTER TABLE promo_code DROP CONSTRAINT FK_3D8C939E97A0ADA3');
        $this->addSql('ALTER TABLE video_view DROP CONSTRAINT FK_F96AF65229C1004E');
        $this->addSql('DROP TABLE activity');
        $this->addSql('DROP TABLE actor');
        $this->addSql('DROP TABLE auth_log');
        $this->addSql('DROP TABLE city');
        $this->addSql('DROP TABLE client_application');
        $this->addSql('DROP TABLE club');
        $this->addSql('DROP TABLE country');
        $this->addSql('DROP TABLE district');
        $this->addSql('DROP TABLE document');
        $this->addSql('DROP TABLE education');
        $this->addSql('DROP TABLE email_dispatch');
        $this->addSql('DROP TABLE email_dispatch_done');
        $this->addSql('DROP TABLE email_dispatch_to');
        $this->addSql('DROP TABLE email_friends_reference');
        $this->addSql('DROP TABLE email_out');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE event_attendance');
        $this->addSql('DROP TABLE event_attendance_import');
        $this->addSql('DROP TABLE event_attendance_placebuy');
        $this->addSql('DROP TABLE event_attendance_ticket');
        $this->addSql('DROP TABLE event_condition');
        $this->addSql('DROP TABLE event_map');
        $this->addSql('DROP TABLE event_out_spot');
        $this->addSql('DROP TABLE fan_card');
        $this->addSql('DROP TABLE fan_card_person');
        $this->addSql('DROP TABLE giveaway_action');
        $this->addSql('DROP TABLE item');
        $this->addSql('DROP TABLE item_how2get');
        $this->addSql('DROP TABLE line_of_work');
        $this->addSql('DROP TABLE log_callcenter');
        $this->addSql('DROP TABLE news');
        $this->addSql('DROP TABLE person');
        $this->addSql('DROP TABLE person_activity');
        $this->addSql('DROP TABLE video_view');
        $this->addSql('DROP TABLE person_event_forecast');
        $this->addSql('DROP TABLE person_points');
        $this->addSql('DROP TABLE person_progress');
        $this->addSql('DROP TABLE person_purchase');
        $this->addSql('DROP TABLE person_subs');
        $this->addSql('DROP TABLE place');
        $this->addSql('DROP TABLE player');
        $this->addSql('DROP TABLE points_status');
        $this->addSql('DROP TABLE progress_items');
        $this->addSql('DROP TABLE promo_action');
        $this->addSql('DROP TABLE promo_code');
        $this->addSql('DROP TABLE promo_code_distribution');
        $this->addSql('DROP TABLE promo_code_distribution_area');
        $this->addSql('DROP TABLE promo_coupon');
        $this->addSql('DROP TABLE promo_coupon_action');
        $this->addSql('DROP TABLE promo_email_in');
        $this->addSql('DROP TABLE promo_sms_in');
        $this->addSql('DROP TABLE promo_sms_out');
        $this->addSql('DROP TABLE push_device_id');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE role_actor');
        $this->addSql('DROP TABLE security');
        $this->addSql('DROP TABLE sms_out');
        $this->addSql('DROP TABLE social_account');
        $this->addSql('DROP TABLE social_post');
        $this->addSql('DROP TABLE social_post_attachments');
        $this->addSql('DROP TABLE social_repost');
        $this->addSql('DROP TABLE social_token');
        $this->addSql('DROP TABLE sport');
        $this->addSql('DROP TABLE sportomat');
        $this->addSql('DROP TABLE subscription');
        $this->addSql('DROP TABLE subs_list');
        $this->addSql('DROP TABLE ticket');
        $this->addSql('DROP TABLE video');
    }
}
