<?php

namespace Zenomania\CoreBundle\Repository;

use Zenomania\CoreBundle\Entity\Badge;

/**
 * BadgeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadgeRepository extends \Doctrine\ORM\EntityRepository
{
    public function save(Badge $badge){
        $this->_em->persist($badge);
        $this->_em->flush($badge);
    }
}
