<?php

namespace Zenomania\CoreBundle\Repository;

/**
 * BadgeTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BadgeTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
