<?php

namespace Zenomania\CoreBundle\Repository;

use Zenomania\CoreBundle\Entity\Order;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends \Doctrine\ORM\EntityRepository
{

    public function getOrderData(Order $order)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qbOrderStatusHistory = clone $qb;

        $selectOrderStatusHistory = $qbOrderStatusHistory->select('s')
            ->from('ZenomaniaCoreBundle:OrderStatusHistory', 's')
            ->where('s.orderId = :order_id')
            ->orderBy('s.createdAt')
            ->setParameter('order_id', $order->getId());
        $resultOrderStatusHistory = $selectOrderStatusHistory->getQuery()->getResult();

        $qbOrderCart = clone $qb;

        $selectOrderCart = $qbOrderCart->select('c')
            ->from('ZenomaniaCoreBundle:OrderCart', 'c')
            ->where('c.orderId = :order_id')
            ->setParameter('order_id', $order->getId());
        $resultOrderCart = $selectOrderCart->getQuery()->getResult();

        $qbOrderDelivery = clone $qb;

        $selectOrderDelivery = $qbOrderDelivery->select('d')
            ->from('ZenomaniaCoreBundle:OrderDelivery', 'd')
            ->where('d.orderId = :order_id')
            ->setParameter('order_id', $order->getId());
        $resultOrderDelivery = $selectOrderDelivery->getQuery()->getOneOrNullResult();

        $result = [
            'orderStatusHistory' => $resultOrderStatusHistory,
            'orderCart' => $resultOrderCart,
            'orderDelivery' => $resultOrderDelivery,
        ];
        return $result;
    }
}