<?php

namespace Zenomania\CoreBundle\Repository;

/**
 * OrderCartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderCartRepository extends \Doctrine\ORM\EntityRepository
{
}
