<?php

namespace Zenomania\CoreBundle\Repository;

/**
 * OrderDeliveryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderDeliveryRepository extends \Doctrine\ORM\EntityRepository
{
}
