<?php

namespace Zenomania\CoreBundle\Repository;

/**
 * OrderStatusHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderStatusHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
