<?php

namespace Zenomania\CoreBundle\Repository;
use Zenomania\CoreBundle\Entity\Payment as PaymentEntity ;

/**
 * PaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentRepository extends \Doctrine\ORM\EntityRepository
{
    public function save(PaymentEntity $payment)
    {
        $this->_em->persist($payment);
        $this->_em->flush();
        return $payment;
    }
}
