services:
    form.user_profile:
        class: Zenomania\ApiBundle\Form\UserProfileType
        arguments: ['@repository.city_repository', '@repository.district_repository']
        tags:
            - { name: form.type }
    form.badge:
        class: Zenomania\ApiBundle\Form\BadgeType
        arguments: ['@repository.badge_type_repository']
        tags:
            - { name: form.type }