parameters:
    api.data.transformer.manager_class: 'Zenomania\ApiBundle\Service\Transformer\Manager'
    api.data.transformer.scope_class: 'Zenomania\ApiBundle\Service\Scope'
    api.data.serializer_class: 'Zenomania\ApiBundle\Service\Serializer\ArraySerializer'

services:
    api.data.serializer:
        class: "%api.data.serializer_class%"
    api.data.transformer.scope_manager:
        class: Zenomania\ApiBundle\Service\Transformer\ScopeManager
        calls:
          - [setScopeClass, ['%api.data.transformer.scope_class%']]
          - [setSerializer, ['@api.data.serializer']]
    api.data.transformer.manager:
        class: "%api.data.transformer.manager_class%"
        arguments: ['@api.data.transformer.scope_manager']
    api.data.transformer.user.profile_transformer:
        class: Zenomania\ApiBundle\Service\Transformer\User\UserProfileTransformer
        arguments: ['@utils.host_based_url', '@repository.person_points_repository']
    api.data.transformer.user.profile_stats_transformer:
        class: Zenomania\ApiBundle\Service\Transformer\User\UserProfileStatsTransformer
    api.data.transformer.club:
        class: Zenomania\ApiBundle\Service\Transformer\ClubTransformer
        arguments: ['@utils.host_based_url']
    api.data.transformer.event.transformer:
        class: Zenomania\ApiBundle\Service\Transformer\Event\EventTransformer
        arguments: ['@utils.host_based_url']
    api.data.transformer.event.prediction:
        class: Zenomania\ApiBundle\Service\Transformer\Event\EventPredictionTransformer
        arguments: ['@utils.host_based_url']
    api.data.transformer.ratings:
        class: Zenomania\ApiBundle\Service\Transformer\RatingsTransformer
        arguments: ['@utils.host_based_url']
    api.data.transformer.players:
        class: Zenomania\ApiBundle\Service\Transformer\PlayerTransformer
        arguments: ['@utils.host_based_url']
    api.data.transformer.badges:
        class: Zenomania\ApiBundle\Service\Transformer\BadgesTransformer
        arguments: ['@utils.host_based_url']
    api.data.transformer.prediction.history:
        class: Zenomania\ApiBundle\Service\Transformer\Event\PredictionHistoryTransformer
        arguments:
            - '@utils.host_based_url'
            - '@api.data.transformer.event.forecast'
    api.data.transformer.event.lineup:
        class: Zenomania\ApiBundle\Service\Transformer\Event\LineUpTransformer
        arguments: ['@utils.host_based_url', '@repository.event_forecast_repository']
    api.data.transformer.event.forecast:
        class: Zenomania\ApiBundle\Service\Transformer\Event\EventForecastTransformer
        arguments:
            - '@utils.host_based_url'
            - '@event.service'
            - '@security.token_storage'
            - '@api.data.transformer.event.lineup_forecast'
            - '@api.data.transformer.event.lineup_mvp_forecast'
    api.data.transformer.event.lineup_forecast:
        class: Zenomania\ApiBundle\Service\Transformer\Event\LineUpForecastTransformer
        arguments:
            - '@utils.host_based_url'
            - '@repository.event_player_forecast_repository'
            - '@security.token_storage'
    api.data.transformer.event.lineup_mvp_forecast:
        class: Zenomania\ApiBundle\Service\Transformer\Event\LineUpMvpForecastTransformer
        parent: api.data.transformer.event.lineup_forecast
    api.data.transformer.news:
        class: Zenomania\ApiBundle\Service\Transformer\NewsTransformer
        arguments: ['@utils.host_based_url', %vk_group_id%]
    api.data.transformer.order:
        class: Zenomania\ApiBundle\Service\Transformer\OrderTransformer
        arguments: ['@utils.host_based_url']
    api.data.transformer.product:
        class: Zenomania\ApiBundle\Service\Transformer\ProductTransformer
        arguments: ['@utils.host_based_url']
