services:
    event.event_dispatcher:
        class: Zenomania\CoreBundle\Event\EventDispatcher
        autowire: true
    event.notification_manager:
        class: Zenomania\CoreBundle\Event\NotificationManager
        arguments: ['@event.event_dispatcher']
    event.listener.registration:
        class: Zenomania\CoreBundle\Event\Listener\RegistrationListener
        arguments: ['@api.invite_bonus_service']
        tags:
            - {name: "kernel.event_listener", event: "user.registration.referral", method: "onReferralCodeAppliedEvent"}
    event.listener.badge.registration:
        class: Zenomania\CoreBundle\Event\Listener\BadgeListener
        arguments: ['@user_badge.service', '@repository.person_repository']
        tags:
            - {name: "kernel.event_listener", event: "user.registration.badge", method: "onRegistrationEvent"}
    event.listener.badge.user_profile:
        class: Zenomania\CoreBundle\Event\Listener\BadgeListener
        arguments: ['@user_badge.service', '@repository.person_repository']
        tags:
            - {name: "kernel.event_listener", event: "user.profile.badge", method: "onUserProfileEvent"}
    event.listener.ticket.registration:
        class: Zenomania\CoreBundle\Event\Listener\TicketListener
        arguments: ['@points.ticket_registration']
        tags:
            - {name: "kernel.event_listener", event: "ticket.registration", method: "onRegistrationEvent"}
    event.listener.club:
        class: Zenomania\CoreBundle\Event\Listener\ClubListener
        arguments: ['@old_sound_rabbit_mq.photo_uploader_producer']
        tags:
            - {name: "kernel.event_listener", event: "club.received", method: "onClubReceivedEvent"}
