services:
    event.event_dispatcher:
        class: Zenomania\CoreBundle\Event\EventDispatcher
        autowire: true
    event.notification_manager:
        class: Zenomania\CoreBundle\Event\NotificationManager
        arguments: ['@event.event_dispatcher']