services:
    core.form.flow.registration:
        class: Zenomania\CoreBundle\Form\Wizard\RegistrationFlow
        arguments: ['@core.service.registration']
        parent: craue.form.flow
    core.service.token_management:
        class: Zenomania\CoreBundle\Service\Token\TokenManagementService
        arguments: ['@service_container']
        abstract: true
    core.service.registration:
        class: Zenomania\CoreBundle\Service\RegistrationService
        parent: core.service.token_management
    core.service.update_phone:
        class: Zenomania\CoreBundle\Service\UpdatePhoneService
        parent: core.service.token_management
    core.service.password_recovery:
        class: Zenomania\CoreBundle\Service\PasswordRecoveryService
        parent: core.service.token_management
    core.service.token.storage:
        class: Zenomania\CoreBundle\Service\Token\Storage
        calls:
            - ['setClient', ['@snc_redis.session']]
    core.service.authenticate:
        class: Zenomania\CoreBundle\Service\AuthenticateService
        arguments: ['@service_container']
