services:
    repository.user_repository:
        class: Zenomania\CoreBundle\Repository\UserRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\User
    repository.ticket_repository:
        class: Zenomania\CoreBundle\Repository\TicketRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\Ticket
    repository.person_points_repository:
        class: Zenomania\CoreBundle\Repository\PersonPointsRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\PersonPoints
    repository.event_attendance_repository:
        class: Zenomania\CoreBundle\Repository\EventAttendanceRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\EventAttendance