services:
    repository.user_repository:
        class: Zenomania\CoreBundle\Repository\UserRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\User
    repository.ticket_repository:
        class: Zenomania\CoreBundle\Repository\TicketRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\Ticket
    repository.person_points_repository:
        class: Zenomania\CoreBundle\Repository\PersonPointsRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\PersonPoints
    repository.person_repository:
        class: Zenomania\CoreBundle\Repository\PersonRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\Person
    repository.club_season_repository:
        class: Zenomania\CoreBundle\Repository\SeasonRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\PromoAction
    repository.subscription_repository:
        class: Zenomania\CoreBundle\Repository\SubscriptionRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\Subscription
    repository.event_attendance_repository:
        class: Zenomania\CoreBundle\Repository\EventAttendanceRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\EventAttendance
    repository.event_repository:
        class: Zenomania\CoreBundle\Repository\EventRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\Event
    repository.social_account_repository:
        class: Zenomania\CoreBundle\Repository\SocialAccountRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\SocialAccount
    repository.user_referral_code_repository:
        class: Zenomania\CoreBundle\Repository\UserReferralCodeRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\UserReferralCode
    repository.user_referral_activation_repository:
        class: Zenomania\CoreBundle\Repository\UserReferralActivationRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\UserReferralActivation
    repository.actor_repository:
        class: Zenomania\CoreBundle\Repository\ActorRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\Actor
    repository.city_repository:
        class: Zenomania\CoreBundle\Repository\CityRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\City
    repository.district_repository:
        class: Zenomania\CoreBundle\Repository\DistrictRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\District