services:
    repository.user_repository:
        class: Zenomania\CoreBundle\Repository\UserRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\User
    repository.ticket_repository:
        class: Zenomania\CoreBundle\Repository\TicketRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\Ticket
    repository.person_points_repository:
        class: Zenomania\CoreBundle\Repository\PersonPointsRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\PersonPoints
    repository.person_repository:
        class: Zenomania\CoreBundle\Repository\PersonRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\Person
    repository.promo_action_repository:
        class: Zenomania\CoreBundle\Repository\PromoActionRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\PromoAction
    repository.subscription_repository:
        class: Zenomania\CoreBundle\Repository\SubscriptionRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\Subscription
    repository.event_attendance_repository:
        class: Zenomania\CoreBundle\Repository\EventAttendanceRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\EventAttendance
    repository.social_account_repository:
        class: Zenomania\CoreBundle\Repository\SocialAccountRepository
        factory: ['@doctrine.orm.default_entity_manager', getRepository]
        arguments:
            - Zenomania\CoreBundle\Entity\SocialAccount