services:
    file.upload:
        class: Zenomania\CoreBundle\Service\Upload\UploadFile
        arguments: ['@service_container']
    file.upload_photo_abstract:
        class: Zenomania\CoreBundle\Service\Upload\UploadPhoto
        arguments: ['@file.upload']
        abstract: true
    file.upload_profile_photo:
        class: Zenomania\CoreBundle\Service\Upload\UploadProfilePhoto
        parent: file.upload_photo_abstract
    file.upload_player_photo:
        class: Zenomania\CoreBundle\Service\Upload\UploadPlayerPhoto
        parent: file.upload_photo_abstract
    file.upload_promo_coupon:
        class: Zenomania\CoreBundle\Service\Upload\UploadPromoCoupon
        parent: file.upload