zenomania_core_homepage:
    path:     /
    defaults: { _controller: ZenomaniaCoreBundle:Default:index }
task_user_role:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/userrole.yml"
    prefix:   /user/role
task_user_status:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/userstatus.yml"
    prefix:   /user/status
task_user:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/user.yml"
    prefix:   /user
zenomania_core_country:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/country.yml"
    prefix:   /country
zenomania_core_district:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/district.yml"
    prefix:   /district
zenomania_core_city:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/city.yml"
    prefix:   /city
zenomania_core_education:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/education.yml"
    prefix:   /education
zenomania_core_club:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/club.yml"
    prefix:   /club
zenomania_core_actor:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/actor.yml"
    prefix:   /actor
zenomania_core_sport:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/sport.yml"
    prefix:   /sport
zenomania_core_event:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/event.yml"
    prefix:   /event
zenomania_core_player:
        resource: "@ZenomaniaCoreBundle/Resources/config/routing/player.yml"
        prefix:   /player
zenomania_core_badge:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/badge.yml"
    prefix:   /badge
zenomania_core_badge_type:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/badgetype.yml"
    prefix:   /badge/type
zenomania_core_promocoupon:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/promocoupon.yml"
    prefix:   /promocoupon
zenomania_core_pointstype:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/pointstype.yml"
    prefix:   /pointstype
zenomania_core_orderstatus:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/orderstatus.yml"
    prefix:   /orderstatus
zenomania_core_product:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/product.yml"
    prefix:   /product
zenomania_core_productcategory:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/productcategory.yml"
    prefix:   /productcategory
login:
    path: /login
    defaults: {_controller: ZenomaniaCoreBundle:Security:login}
register:
    path: /register
    defaults: {_controller: ZenomaniaCoreBundle:Security:register}
recover:
    path: /recover
    defaults: {_controller: ZenomaniaCoreBundle:Security:recoverySendMessage}
recover_code:
    path: /recover/{code}
    defaults: {_controller: ZenomaniaCoreBundle:Security:recoveryChangePassword}
logout:
    path: /logout
