zenomania_core_homepage:
    path:     /
    defaults: { _controller: ZenomaniaCoreBundle:Default:index }
task_user_role:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/userrole.yml"
    prefix:   /user/role
task_user_status:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/userstatus.yml"
    prefix:   /user/status
task_user:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/user.yml"
    prefix:   /user
zenomania_core_country:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/country.yml"
    prefix:   /country
zenomania_core_district:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/district.yml"
    prefix:   /district
zenomania_core_city:
    resource: "@ZenomaniaCoreBundle/Resources/config/routing/city.yml"
    prefix:   /city
login:
    path: /login
    defaults: {_controller: ZenomaniaCoreBundle:Security:login}
register:
    path: /register
    defaults: {_controller: ZenomaniaCoreBundle:Security:register}
recover:
    path: /recover
    defaults: {_controller: ZenomaniaCoreBundle:Security:recoverySendMessage}
recover_code:
    path: /recover/{code}
    defaults: {_controller: ZenomaniaCoreBundle:Security:recoveryChangePassword}
logout:
    path: /logout
