imports:
   - { resource: "services/repositories.yml" }
   - { resource: "services/registration.yml" }

services:
#    zenomania_core.example:
#        class: Zenomania\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
