badge_type_index:
    path:     /
    defaults: { _controller: "ZenomaniaCoreBundle:BadgeType:index" }
    methods:  GET

badge_type_show:
    path:     /{id}/show
    defaults: { _controller: "ZenomaniaCoreBundle:BadgeType:show" }
    methods:  GET

badge_type_new:
    path:     /new
    defaults: { _controller: "ZenomaniaCoreBundle:BadgeType:new" }
    methods:  [GET, POST]

badge_type_edit:
    path:     /{id}/edit
    defaults: { _controller: "ZenomaniaCoreBundle:BadgeType:edit" }
    methods:  [GET, POST]

badge_type_delete:
    path:     /{id}/delete
    defaults: { _controller: "ZenomaniaCoreBundle:BadgeType:delete" }
    methods:  DELETE
