badge_index:
    path:     /
    defaults: { _controller: "ZenomaniaCoreBundle:Badge:index" }
    methods:  GET

badge_show:
    path:     /{id}/show
    defaults: { _controller: "ZenomaniaCoreBundle:Badge:show" }
    methods:  GET

badge_new:
    path:     /new
    defaults: { _controller: "ZenomaniaCoreBundle:Badge:new" }
    methods:  [GET, POST]

badge_edit:
    path:     /{id}/edit
    defaults: { _controller: "ZenomaniaCoreBundle:Badge:edit" }
    methods:  [GET, POST]

badge_delete:
    path:     /{id}/delete
    defaults: { _controller: "ZenomaniaCoreBundle:Badge:delete" }
    methods:  DELETE
