order_index:
    path:     /
    defaults: { _controller: "ZenomaniaCoreBundle:Order:index" }
    methods:  GET

order_show:
    path:     /{id}/show
    defaults: { _controller: "ZenomaniaCoreBundle:Order:show" }
    methods:  GET

order_new:
    path:     /new
    defaults: { _controller: "ZenomaniaCoreBundle:Order:new" }
    methods:  [GET, POST]

order_edit:
    path:     /{id}/edit
    defaults: { _controller: "ZenomaniaCoreBundle:Order:edit" }
    methods:  [GET, POST]

order_delete:
    path:     /{id}/delete
    defaults: { _controller: "ZenomaniaCoreBundle:Order:delete" }
    methods:  DELETE
