sport_index:
    path:     /
    defaults: { _controller: "ZenomaniaCoreBundle:Sport:index" }
    methods:  GET

sport_show:
    path:     /{id}/show
    defaults: { _controller: "ZenomaniaCoreBundle:Sport:show" }
    methods:  GET

sport_new:
    path:     /new
    defaults: { _controller: "ZenomaniaCoreBundle:Sport:new" }
    methods:  [GET, POST]

sport_edit:
    path:     /{id}/edit
    defaults: { _controller: "ZenomaniaCoreBundle:Sport:edit" }
    methods:  [GET, POST]

sport_delete:
    path:     /{id}/delete
    defaults: { _controller: "ZenomaniaCoreBundle:Sport:delete" }
    methods:  DELETE
