user_status_index:
    path:     /
    defaults: { _controller: "ZenomaniaCoreBundle:UserStatus:index" }
    methods:  GET

user_status_show:
    path:     /{id}/show
    defaults: { _controller: "ZenomaniaCoreBundle:UserStatus:show" }
    methods:  GET

user_status_new:
    path:     /new
    defaults: { _controller: "ZenomaniaCoreBundle:UserStatus:new" }
    methods:  [GET, POST]

user_status_edit:
    path:     /{id}/edit
    defaults: { _controller: "ZenomaniaCoreBundle:UserStatus:edit" }
    methods:  [GET, POST]

user_status_delete:
    path:     /{id}/delete
    defaults: { _controller: "ZenomaniaCoreBundle:UserStatus:delete" }
    methods:  DELETE
