user_index:
    path:     /
    defaults: { _controller: "ZenomaniaCoreBundle:User:index" }
    methods:  GET

user_search_pagination:
    path:     /search_pagination
    defaults: { _controller: "ZenomaniaCoreBundle:User:searchPagination" }
    methods:  POST

user_show:
    path:     /{id}/show
    defaults: { _controller: "ZenomaniaCoreBundle:User:show" }
    methods:  GET

user_new:
    path:     /new
    defaults: { _controller: "ZenomaniaCoreBundle:User:new" }
    methods:  [GET, POST]

user_edit:
    path:     /{id}/edit
    defaults: { _controller: "ZenomaniaCoreBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /{id}/delete
    defaults: { _controller: "ZenomaniaCoreBundle:User:delete" }
    methods:  DELETE

user_profile:
    path:     /{id}/profile
    defaults: {_controller: "ZenomaniaCoreBundle:User:profile"}
    methods:  [GET, POST]

user_search:
    path:     /search
    defaults: {_controller: "ZenomaniaCoreBundle:User:search"}
    methods:  [GET, POST]
